import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';

import { assertValidDesignDna, validateDesignDna } from './design-dna.mjs';
import { DesignomeError } from './errors.mjs';
import {
  atomicWrite,
  jsonText,
  pathExists,
  pluginRoot,
  readJson,
  readTextIfExists,
  relativeInside,
  resolveProjectPath,
  sha256,
  toPosixPath,
} from './files.mjs';
import { inspectManagedBlock, upsertManagedBlock } from './markers.mjs';

const manifestRelativePath = '.designome/manifest.json';
const installedDnaRelativePath = '.designome/design-dna.json';
const auditConfigRelativePath = '.designome/audit.config.json';
const defaultDocumentationDirectory = 'docs/designome';
const auditSkillRelativeDirectory = '.agents/skills/designome-audit';
const transactionRelativePath = '.designome/install-transaction.json';
const supportedManifestVersions = new Set(['0.1.0', '0.2.0']);
const cssStartMarker = '/* designome:generated-import:start */';
const cssEndMarker = '/* designome:generated-import:end */';
const guidanceStartMarker = '<!-- designome:guidance:start -->';
const guidanceEndMarker = '<!-- designome:guidance:end -->';

const cssCandidates = [
  'src/app/globals.css',
  'app/globals.css',
  'src/styles/globals.css',
  'styles/globals.css',
  'src/index.css',
  'src/main.css',
];

function safeCssComment(value) {
  return String(value)
    .replace(/\*\//gu, '* /')
    .replace(/[\r\n]+/gu, ' ');
}

function cssName(tokenId) {
  return tokenId
    .replace(/^token\./u, '')
    .replace(/[^a-zA-Z0-9-]+/gu, '-')
    .replace(/-+/gu, '-')
    .replace(/^-|-$/gu, '')
    .toLowerCase();
}

function cssValue(value, tokenId) {
  const rendered = String(value);
  if (
    /[;{}\r\n]/u.test(rendered) ||
    rendered.includes('/*') ||
    rendered.includes('*/')
  ) {
    throw new DesignomeError(`Unsafe literal CSS value in ${tokenId}`, {
      code: 'UNSAFE_CSS_TOKEN',
    });
  }
  return rendered;
}

function renderGeneratedCss(dna, scope, styling) {
  const exactTokens = [];
  const nonLiteralTokens = [];
  const generatedNames = new Set();
  for (const token of dna.tokens) {
    const generatedName = cssName(token.id);
    if (generatedNames.has(generatedName)) {
      throw new DesignomeError(`CSS token name collision for ${token.id}`, {
        code: 'CSS_TOKEN_COLLISION',
      });
    }
    generatedNames.add(generatedName);
    if (token.value?.kind === 'exact') {
      exactTokens.push(
        `    --designome-${generatedName}: ${cssValue(token.value.value, token.id)};`,
      );
    } else if (
      token.value?.kind === 'range' &&
      token.value.strategy === 'bounded' &&
      Number.isFinite(token.value.preferred)
    ) {
      exactTokens.push(
        `    --designome-${generatedName}: ${cssValue(`${token.value.preferred}${token.value.unit}`, token.id)};`,
      );
      nonLiteralTokens.push(
        `  /* ${safeCssComment(token.id)} bounds: ${token.value.minimum} to ${token.value.maximum} ${safeCssComment(token.value.unit)} */`,
      );
    } else {
      const explanation =
        token.value?.expression ??
        token.value?.reason ??
        (token.value?.kind === 'range'
          ? `${token.value.minimum} to ${token.value.maximum} ${token.value.unit}`
          : 'No literal CSS value is available.');
      nonLiteralTokens.push(
        `  /* ${safeCssComment(token.id)}: ${safeCssComment(explanation)} */`,
      );
    }
  }

  const lines = [
    `/* Generated by Designome from ${safeCssComment(dna.documentId)} revision ${dna.revision.number}. */`,
    '/* Do not edit this file. Put project-owned changes in designome.overrides.css. */',
    `/* Styling adapter: ${safeCssComment(styling.strategy)} (${safeCssComment(styling.system)} detected). */`,
    '',
    '@layer designome.tokens {',
    `  ${scope} {`,
    ...(exactTokens.length > 0
      ? exactTokens
      : ['    /* No exact token values were accepted. */']),
    '  }',
    ...(nonLiteralTokens.length > 0 ? ['', ...nonLiteralTokens] : []),
    '}',
    '',
  ];
  return lines.join('\n');
}

function renderOverridesCss() {
  return [
    '/* Project-owned Designome overrides. This file is never overwritten. */',
    '@layer designome.overrides {',
    '  /* Add intentional local overrides here. */',
    '}',
    '',
  ].join('\n');
}

function renderAuditConfig() {
  return jsonText({
    schemaVersion: '1.0.0',
    baseUrl: 'http://127.0.0.1:3000',
    outputDirectory: 'audit',
    layers: {
      installation: true,
      mechanical: true,
      perceptual: true,
      usage: true,
    },
    routes: [
      {
        id: 'overview',
        path: '/',
        viewports: [
          { name: 'desktop', width: 1440, height: 1000 },
          { name: 'mobile', width: 390, height: 844 },
        ],
        flows: ['load the route'],
        scenarios: ['default', 'loading', 'empty', 'error', 'recovery'],
        directions: ['ltr'],
      },
    ],
  });
}

function renderCssImportBlock(generatedName, overridesName) {
  return [
    cssStartMarker,
    `@import "./${generatedName}";`,
    `@import "./${overridesName}";`,
    cssEndMarker,
    '',
  ].join('\n');
}

function renderGuidanceBlock({
  documentationDirectory,
  integrationPolicy,
  styling,
}) {
  const existingRules = integrationPolicy.existingRulePaths.length
    ? integrationPolicy.existingRulePaths
        .map((item) => `\`${item}\``)
        .join(', ')
    : 'none declared';
  const stylingInstruction =
    styling.strategy === 'shadcn-components'
      ? 'Prefer installed shadcn/ui components, semantic theme tokens, configured aliases, and the declared icon library. Do not reinitialize or overwrite components without explicit approval.'
      : styling.system === 'tailwind'
        ? "Prefer the project's existing Tailwind utilities and theme conventions before adding new component CSS."
        : "Prefer the project's existing styling primitives before adding a parallel component system.";
  const uiKitInstruction =
    styling.uiKit?.status === 'proposed'
      ? ' A shadcn/ui greenfield preference is recorded as proposed; do not initialize or install it without separate explicit authorization.'
      : '';
  return [
    guidanceStartMarker,
    '## Designome-generated UI',
    '',
    `Read \`${documentationDirectory}/README.md\` and \`.designome/design-dna.json\` before generating UI.`,
    `Repository rule precedence is \`${integrationPolicy.rulePrecedence}\`; declared existing UI rules: ${existingRules}.`,
    `The detected styling adapter is \`${styling.strategy}\`. ${stylingInstruction}${uiKitInstruction}`,
    'Preserve claim status, cover applicable business states and stress cases, and run `$designome-audit` before delivery.',
    guidanceEndMarker,
    '',
  ].join('\n');
}

function markdownValue(value) {
  if (value?.kind === 'exact') return `Exact: \`${String(value.value)}\``;
  if (value?.kind === 'range')
    return `Range: ${value.minimum}–${value.maximum} ${value.unit}${Number.isFinite(value.preferred) ? `; preferred ${value.preferred} ${value.unit}; strategy \`${value.strategy}\`` : ''}`;
  if (value?.kind === 'relationship') return value.expression;
  return value?.reason ?? 'Unknown';
}

function claimDetails(claim) {
  const evidence = claim.evidenceRefs?.length
    ? claim.evidenceRefs.map((item) => `\`${item}\``).join(', ')
    : 'none; this is not an observed claim';
  const exceptions = claim.exceptions?.length
    ? claim.exceptions.join('; ')
    : 'None documented.';
  return [
    `- Status: \`${claim.epistemicStatus}\``,
    `- Confidence: ${claim.confidence.score} — ${claim.confidence.basis}`,
    `- Scope: ${claim.scope.join(', ')}`,
    `- Evidence: ${evidence}`,
    `- Exceptions: ${exceptions}`,
    `- Validation: ${claim.validation.method}`,
  ].join('\n');
}

function renderRulesDocument(dna) {
  const rules = dna.rules.map((rule) =>
    [
      `## ${rule.name}`,
      '',
      `- Rule ID: \`${rule.id}\``,
      `- Strength: \`${rule.strength}\``,
      `- Category: \`${rule.category}\``,
      `- Epistemic status: \`${rule.claim.epistemicStatus}\``,
      '',
      rule.claim.statement,
      '',
      '### Requirements',
      '',
      ...rule.requirements.map((item) => `- ${item}`),
      '',
      '### Validation cases',
      '',
      ...rule.validationCases.map((item) => `- ${item}`),
      '',
      claimDetails(rule.claim),
    ].join('\n'),
  );
  return [
    '# UI rules',
    '',
    `Accepted Design DNA: \`${dna.documentId}\` revision ${dna.revision.number}.`,
    '',
    ...rules,
    '',
  ].join('\n');
}

function renderIntegrationDocument({
  dna,
  styling,
  integrationPolicy,
  documentationDirectory,
}) {
  const evidence = styling.evidence.length
    ? styling.evidence.map((item) => `- ${item}`)
    : ['- No styling-system marker was detected.'];
  const existing = integrationPolicy.existingRulePaths.length
    ? integrationPolicy.existingRulePaths.map((item) => `- \`${item}\``)
    : ['- None declared.'];
  return [
    '# Repository integration',
    '',
    `This project installs \`${dna.documentId}\` revision ${dna.revision.number}. Designome documentation is managed in \`${documentationDirectory}\`.`,
    '',
    '- Technical context status: `observed` in the target repository; it is not screenshot evidence.',
    '',
    '## Styling context',
    '',
    `- Detected system: \`${styling.system}\``,
    `- Integration strategy: \`${styling.strategy}\``,
    `- Detected version: ${styling.version ? `\`${styling.version}\`` : 'unknown'}`,
    `- UI kit preference: \`${styling.uiKit?.preference ?? 'auto'}\``,
    `- UI kit status: \`${styling.uiKit?.status ?? 'not-detected'}\``,
    ...evidence,
    '',
    styling.strategy === 'shadcn-components'
      ? 'Reuse installed shadcn/ui source components and semantic theme tokens first. Respect the configured aliases, React Server Components mode, primitive base, and icon library. Adding or updating components requires a dry-run and explicit authorization; never reinitialize or overwrite a customized component silently.'
      : styling.system === 'tailwind'
        ? 'Use existing Tailwind utilities and theme conventions first. Treat `designome.generated.css` as a namespaced semantic-token bridge, not as permission to build a parallel raw-CSS component system.'
        : 'Use the project styling primitives first. Keep Designome CSS namespaced and avoid creating a parallel component system.',
    '',
    '## Rule precedence',
    '',
    `Policy: \`${integrationPolicy.rulePrecedence}\`.`,
    '',
    integrationPolicy.rulePrecedence === 'complement'
      ? 'Existing repository rules remain authoritative where they speak; Designome fills documented gaps. Contradictions require explicit review.'
      : integrationPolicy.rulePrecedence === 'existing-first'
        ? 'Existing repository rules take precedence. Designome deviations must be recorded in the audit.'
        : 'Accepted Designome rules take precedence for generated UI. Existing-rule conflicts must still be reported and never trigger silent rewrites.',
    '',
    '### Declared existing UI rules',
    '',
    ...existing,
    '',
    'Never mine existing project CSS or components as screenshot evidence. Repository context changes implementation shape, not the meaning or epistemic status of the Design DNA.',
    '',
  ].join('\n');
}

function renderComponentMappingDocument(dna, styling) {
  const installed = styling.shadcn?.installedComponents ?? [];
  const patterns = dna.componentPatterns ?? [];
  if (styling.strategy !== 'shadcn-components') {
    const proposal =
      styling.uiKit?.status === 'proposed'
        ? 'A greenfield shadcn/ui setup was requested. Initialization remains a proposed technical action and requires separate explicit authorization before Designome can map components.'
        : "No shadcn/ui adapter is active. Use the project's current component and styling primitives.";
    return [
      '# Component mapping',
      '',
      `- Adapter status: \`${styling.uiKit?.status ?? 'not-detected'}\``,
      '- Epistemic status: `proposed`',
      '',
      proposal,
      '',
    ].join('\n');
  }
  const candidateNames = [
    ['button', 'button'],
    ['action', 'button'],
    ['dialog', 'dialog'],
    ['modal', 'dialog'],
    ['table', 'table'],
    ['list', 'table'],
    ['avatar', 'avatar'],
    ['status', 'badge'],
    ['badge', 'badge'],
    ['search', 'input'],
    ['filter', 'input'],
  ];
  const rows = patterns.map((pattern) => {
    const haystack = `${pattern.id} ${pattern.name}`.toLowerCase();
    const candidate = candidateNames.find(([term]) => haystack.includes(term));
    const component = candidate?.[1] ?? null;
    const available = component ? installed.includes(component) : false;
    return `| ${pattern.name} | ${component ? `\`${component}\`` : 'No direct candidate'} | ${available ? 'Reuse installed source' : component ? 'Propose review; do not install automatically' : 'Implement with existing project primitives'} | \`proposed\` |`;
  });
  return [
    '# Component mapping',
    '',
    'This is technical implementation guidance, not screenshot evidence. Every mapping remains `proposed` until reviewed in the target repository.',
    '',
    `Installed shadcn/ui sources detected: ${installed.length ? installed.map((item) => `\`${item}\``).join(', ') : 'none'}.`,
    '',
    '| Designome pattern | shadcn/ui candidate | Decision | Status |',
    '| ------------------ | ------------------- | -------- | ------ |',
    ...(rows.length
      ? rows
      : [
          '| No canonical component patterns | No direct candidate | Reuse only explicit project components | `proposed` |',
        ]),
    '',
    'Respect configured aliases, React Server Components mode, primitive base, icon library, semantic variables, and local source customizations. Never initialize, add, or overwrite a component without separate authorization.',
    '',
  ].join('\n');
}

function sharesValue(left = [], right = []) {
  const rightValues = new Set(right);
  return left.some((item) => rightValues.has(item));
}

function relevantConcepts(matrix, entry) {
  return matrix.concepts.filter((concept) =>
    entry.conceptRefs.includes(concept.id),
  );
}

function renderRelevantUnknowns(unknowns) {
  if (!unknowns.length) {
    return [
      '## Relevant unknowns',
      '',
      '- Status: `unknown`',
      '- No unresolved question is currently routed to this document. Absence of an unknown is not evidence that every behavior has been observed.',
    ].join('\n');
  }
  return [
    '## Relevant unknowns',
    '',
    ...unknowns.flatMap((item) => [
      `### ${item.question}`,
      '',
      '- Status: `unknown`',
      `- Impact: \`${item.impact}\``,
      `- Resolution: ${item.resolutionPlan}`,
      '',
    ]),
  ].join('\n');
}

function renderStressTests(concepts) {
  const tests = [
    ...new Set(concepts.flatMap((concept) => concept.stressTests)),
  ];
  return [
    '## Required stress tests',
    '',
    ...(tests.length
      ? tests.map((item) => `- Status: \`proposed\` — ${item}`)
      : [
          '- Status: `proposed` — Validate this guidance against the generated implementation before promotion.',
        ]),
  ].join('\n');
}

function renderGenericDocument(dna, matrix, entry) {
  const tokens = dna.tokens.filter(
    (token) =>
      entry.tokenCategories.includes(token.category) ||
      sharesValue(token.claim.conceptRefs, entry.conceptRefs),
  );
  const rules = dna.rules.filter(
    (rule) =>
      entry.ruleCategories.includes(rule.category) ||
      sharesValue(rule.claim.conceptRefs, entry.conceptRefs),
  );
  const unknowns = dna.unknowns.filter((item) =>
    sharesValue(item.conceptRefs, entry.conceptRefs),
  );
  const tokenSections = tokens.flatMap((token) => [
    `### Token: ${token.name}`,
    '',
    token.claim.statement,
    '',
    `- Design value: ${markdownValue(token.value)}`,
    claimDetails(token.claim),
    '',
  ]);
  const ruleSections = rules.flatMap((rule) => [
    `### Rule: ${rule.name}`,
    '',
    rule.claim.statement,
    '',
    `- Strength: \`${rule.strength}\``,
    `- Category: \`${rule.category}\``,
    ...rule.requirements.map((item) => `- Requirement: ${item}`),
    ...rule.validationCases.map((item) => `- Validation case: ${item}`),
    claimDetails(rule.claim),
    '',
  ]);
  return [
    `# ${entry.title}`,
    '',
    entry.purpose,
    '',
    '## Routed Design DNA guidance',
    '',
    ...(tokenSections.length || ruleSections.length
      ? [...tokenSections, ...ruleSections]
      : [
          '- Status: `unknown`',
          '- No accepted token or rule currently covers this subject. Use the proposed stress tests below; do not treat them as screenshot evidence.',
          '',
        ]),
    renderStressTests(relevantConcepts(matrix, entry)),
    '',
    renderRelevantUnknowns(unknowns),
    '',
  ].join('\n');
}

function renderComponentCatalogue(dna) {
  const components = dna.componentPatterns ?? [];
  return [
    '# Component catalogue',
    '',
    'Reusable patterns supported by accepted Design DNA. This is not permission to invent additional page families or roles.',
    '',
    ...(components.length
      ? components.flatMap((component) => [
          `## ${component.name}`,
          '',
          component.claim.statement,
          '',
          `- Component ID: \`${component.id}\``,
          `- Variants: ${component.variants.join('; ')}`,
          `- Rule references: ${component.ruleRefs.map((item) => `\`${item}\``).join(', ') || 'none'}`,
          `- Token references: ${component.tokenRefs.map((item) => `\`${item}\``).join(', ') || 'none'}`,
          claimDetails(component.claim),
          '',
        ])
      : [
          '## No accepted component pattern',
          '',
          '- Status: `unknown`',
          '- The screenshots and accepted synthesis do not support a reusable component catalogue yet.',
          '',
        ]),
  ].join('\n');
}

function renderComponentAnatomy(dna) {
  const components = dna.componentPatterns ?? [];
  return [
    '# Component anatomy',
    '',
    'Anatomy inherits the epistemic status, evidence, scope, and exceptions of its component claim.',
    '',
    ...(components.length
      ? components.flatMap((component) => [
          `## ${component.name}`,
          '',
          ...component.anatomy.map((item) => `- ${item}`),
          '',
          claimDetails(component.claim),
          '',
        ])
      : [
          '- Status: `unknown`',
          '- No component anatomy has been accepted.',
          '',
        ]),
  ].join('\n');
}

function renderComponentStates(dna) {
  const components = dna.componentPatterns ?? [];
  return [
    '# Component states',
    '',
    'Each state carries its own status. Proposed states are resilience contracts, not observed screenshot behavior.',
    '',
    ...(components.length
      ? components.flatMap((component) => [
          `## ${component.name}`,
          '',
          ...component.states.map(
            (state) =>
              `- **${state.name}** — Status: \`${state.status}\` — ${state.behavior}`,
          ),
          '',
        ])
      : [
          '- Status: `unknown`',
          '- No component state matrix has been accepted.',
          '',
        ]),
  ].join('\n');
}

function renderEvidenceDocument(dna) {
  const evidenceBySource = new Map(
    dna.sources.map((source) => [source.id, []]),
  );
  for (const evidence of dna.evidence) {
    if (!evidenceBySource.has(evidence.sourceRef)) {
      evidenceBySource.set(evidence.sourceRef, []);
    }
    evidenceBySource.get(evidence.sourceRef).push(evidence);
  }
  const confidenceClaims = [
    ...dna.tokens.map((item) => ({ id: item.id, claim: item.claim })),
    ...dna.rules.map((item) => ({ id: item.id, claim: item.claim })),
    ...(dna.componentPatterns ?? []).map((item) => ({
      id: item.id,
      claim: item.claim,
    })),
  ];
  return [
    '# Evidence and confidence',
    '',
    'Screenshot regions are the only source of visual truth. Repository code and styling affect integration only.',
    '',
    '## Evidence register',
    '',
    ...dna.sources.flatMap((source) => [
      `### ${source.label}`,
      '',
      '- Status: `observed`',
      `- Source ID: \`${source.id}\``,
      `- Kind: \`${source.kind}\``,
      `- Limitations: ${source.limitations.join('; ')}`,
      '',
      ...(evidenceBySource.get(source.id) ?? []).flatMap((evidence) => [
        `#### ${evidence.region}`,
        '',
        `- Evidence ID: \`${evidence.id}\``,
        `- Visible summary: ${evidence.visibleSummary}`,
        `- Limitations: ${evidence.limitations.join('; ')}`,
        '',
      ]),
    ]),
    '## Claim confidence register',
    '',
    ...confidenceClaims.map(
      ({ id, claim }) =>
        `- \`${id}\` — Status: \`${claim.epistemicStatus}\`; confidence: ${claim.confidence.score}; basis: ${claim.confidence.basis}`,
    ),
    '',
  ].join('\n');
}

function renderUnknownsDocument(dna) {
  const claims = [
    ...dna.tokens.map((item) => ({ id: item.id, claim: item.claim })),
    ...dna.rules.map((item) => ({ id: item.id, claim: item.claim })),
    ...(dna.componentPatterns ?? []).map((item) => ({
      id: item.id,
      claim: item.claim,
    })),
  ];
  const exceptions = claims.filter(({ claim }) => claim.exceptions.length);
  return [
    '# Unknowns and exceptions',
    '',
    'Unknowns are unresolved questions. Exceptions preserve the stated limits of accepted claims.',
    '',
    renderRelevantUnknowns(dna.unknowns),
    '',
    '## Claim exceptions',
    '',
    ...(exceptions.length
      ? exceptions.flatMap(({ id, claim }) => [
          `### ${id}`,
          '',
          `- Claim status: \`${claim.epistemicStatus}\``,
          ...claim.exceptions.map((item) => `- Exception: ${item}`),
          '',
        ])
      : [
          '- Status: `unknown`',
          '- No exception is documented; this does not prove that no exception exists.',
          '',
        ]),
  ].join('\n');
}

function renderCalibrationDocument(dna, matrix, entry) {
  const tokens = dna.tokens.filter((token) =>
    entry.tokenCategories.includes(token.category),
  );
  const rules = dna.rules.filter((rule) =>
    entry.ruleCategories.includes(rule.category),
  );
  return [
    '# Calibration',
    '',
    'Calibration never promotes a measured or proposed value to observed. Exact values require accepted Design DNA evidence.',
    '',
    '## Current calibration inputs',
    '',
    ...(tokens.length
      ? tokens.flatMap((token) => [
          `### ${token.name}`,
          '',
          `- Value: ${markdownValue(token.value)}`,
          claimDetails(token.claim),
          '',
        ])
      : [
          '- Status: `unknown`',
          '- No bounded typography, spacing, or size calibration is currently accepted.',
          '',
        ]),
    '## Calibration rules',
    '',
    ...(rules.length
      ? rules.map(
          (rule) =>
            `- \`${rule.id}\` — Status: \`${rule.claim.epistemicStatus}\` — ${rule.claim.statement}`,
        )
      : ['- Status: `unknown` — No dedicated calibration rule is accepted.']),
    '',
    renderStressTests(relevantConcepts(matrix, entry)),
    '',
  ].join('\n');
}

function renderDocumentationReadme(dna, matrix) {
  const groups = new Map();
  for (const entry of matrix.documentationProjection) {
    const directory = entry.path.split('/')[0];
    if (!groups.has(directory)) groups.set(directory, []);
    groups.get(directory).push(entry);
  }
  return [
    '# Designome UI documentation',
    '',
    `Design DNA: \`${dna.documentId}\`, revision ${dna.revision.number}, status \`${dna.status}\`. Documentation layout: \`${matrix.documentationLayoutVersion}\`.`,
    '',
    'This complete dossier is generated from accepted Design DNA. Every UI claim remains `observed`, `inferred`, `proposed`, or `unknown`; proposed resilience guidance is never presented as screenshot evidence.',
    '',
    'These files are checksum-managed by Designome. Put manual additions in repository-owned documentation or Designome override files rather than editing generated documents.',
    '',
    ...[...groups].flatMap(([directory, entries]) => [
      `## ${directory[0].toUpperCase()}${directory.slice(1)}`,
      '',
      ...entries.map(
        (entry) => `- [${entry.title}](./${entry.path}) — ${entry.purpose}`,
      ),
      '',
    ]),
  ].join('\n');
}

function renderDocumentation({
  dna,
  styling,
  integrationPolicy,
  documentationDirectory,
  matrix,
}) {
  const documents = new Map([
    ['README.md', renderDocumentationReadme(dna, matrix)],
  ]);
  for (const entry of matrix.documentationProjection) {
    const content =
      entry.renderer === 'component-catalogue'
        ? renderComponentCatalogue(dna)
        : entry.renderer === 'component-anatomy'
          ? renderComponentAnatomy(dna)
          : entry.renderer === 'component-states'
            ? renderComponentStates(dna)
            : entry.renderer === 'component-mapping'
              ? renderComponentMappingDocument(dna, styling)
              : entry.renderer === 'rules'
                ? renderRulesDocument(dna)
                : entry.renderer === 'evidence'
                  ? renderEvidenceDocument(dna)
                  : entry.renderer === 'unknowns'
                    ? renderUnknownsDocument(dna)
                    : entry.renderer === 'calibration'
                      ? renderCalibrationDocument(dna, matrix, entry)
                      : entry.renderer === 'integration'
                        ? renderIntegrationDocument({
                            dna,
                            styling,
                            integrationPolicy,
                            documentationDirectory,
                          })
                        : renderGenericDocument(dna, matrix, entry);
    documents.set(entry.path, content);
  }
  return documents;
}

async function detectStylingContext(
  projectRoot,
  cssEntryPath,
  requestedStrategy,
  uiKitPreference,
) {
  const packagePath = path.join(projectRoot, 'package.json');
  const packageJson = (await pathExists(packagePath))
    ? await readJson(packagePath)
    : {};
  const dependencies = {
    ...(packageJson.dependencies ?? {}),
    ...(packageJson.devDependencies ?? {}),
  };
  const css = (await readTextIfExists(cssEntryPath)) ?? '';
  const shadcnPath = path.join(projectRoot, 'components.json');
  const shadcnConfig = (await pathExists(shadcnPath))
    ? await readJson(shadcnPath)
    : null;
  const tailwindVersion = dependencies.tailwindcss ?? null;
  const tailwindEvidence = [];
  if (tailwindVersion)
    tailwindEvidence.push(
      `package.json declares tailwindcss ${tailwindVersion}`,
    );
  if (dependencies['@tailwindcss/postcss'])
    tailwindEvidence.push('package.json declares @tailwindcss/postcss');
  if (
    /@import\s+["']tailwindcss["']/u.test(css) ||
    /@tailwind\s+(?:base|components|utilities)/u.test(css)
  )
    tailwindEvidence.push('The CSS entry contains a Tailwind directive');
  const detectedSystem = shadcnConfig
    ? 'shadcn'
    : tailwindEvidence.length
      ? 'tailwind'
      : 'css';
  const shadcnEvidence = shadcnConfig
    ? [
        'components.json declares a shadcn/ui project',
        ...(shadcnConfig.tailwind?.cssVariables === true
          ? ['components.json enables CSS-variable theming']
          : []),
      ]
    : [];
  const strategy =
    requestedStrategy === 'auto'
      ? detectedSystem === 'shadcn' && uiKitPreference !== 'none'
        ? 'shadcn-components'
        : tailwindEvidence.length > 0
          ? 'tailwind-utilities'
          : 'css-variables'
      : requestedStrategy;
  if (
    strategy === 'tailwind-utilities' &&
    !['tailwind', 'shadcn'].includes(detectedSystem)
  ) {
    throw new DesignomeError(
      'Tailwind strategy was requested but Tailwind was not detected',
      { code: 'STYLE_STRATEGY_UNAVAILABLE' },
    );
  }
  if (strategy === 'shadcn-components' && !shadcnConfig) {
    throw new DesignomeError(
      'shadcn/ui strategy was requested but components.json was not detected',
      { code: 'STYLE_STRATEGY_UNAVAILABLE' },
    );
  }
  const componentDirectories = [];
  if (shadcnConfig) {
    const alias = shadcnConfig.aliases?.ui;
    if (typeof alias === 'string') {
      if (alias.startsWith('@/'))
        componentDirectories.push(
          path.join(projectRoot, 'src', alias.slice(2)),
        );
      else if (!alias.startsWith('@'))
        componentDirectories.push(path.resolve(projectRoot, alias));
    }
    componentDirectories.push(
      path.join(projectRoot, 'src', 'components', 'ui'),
      path.join(projectRoot, 'components', 'ui'),
    );
  }
  const installedComponents = new Set();
  for (const directory of componentDirectories) {
    relativeInside(projectRoot, directory, 'shadcn component directory');
    const entries = await fs
      .readdir(directory, { withFileTypes: true })
      .catch((error) => {
        if (error.code === 'ENOENT') return [];
        throw error;
      });
    for (const entry of entries) {
      if (entry.isFile() && /\.[cm]?[jt]sx?$/u.test(entry.name))
        installedComponents.add(entry.name.replace(/\.[^.]+$/u, ''));
    }
  }
  return {
    system: detectedSystem,
    strategy,
    version: tailwindVersion,
    evidence: [...shadcnEvidence, ...tailwindEvidence],
    uiKit: shadcnConfig
      ? {
          preference: uiKitPreference,
          status: strategy === 'shadcn-components' ? 'reuse' : 'disabled',
        }
      : uiKitPreference === 'shadcn'
        ? {
            preference: uiKitPreference,
            status: 'proposed',
            requiredAction:
              'Review and explicitly authorize shadcn/ui initialization before changing the target project.',
          }
        : { preference: uiKitPreference, status: 'not-detected' },
    ...(shadcnConfig
      ? {
          shadcn: {
            style: shadcnConfig.style ?? null,
            base: shadcnConfig.base ?? null,
            iconLibrary: shadcnConfig.iconLibrary ?? null,
            rsc: shadcnConfig.rsc ?? null,
            cssVariables: shadcnConfig.tailwind?.cssVariables ?? null,
            aliases: shadcnConfig.aliases ?? {},
            installedComponents: [...installedComponents].sort(),
          },
        }
      : {}),
  };
}

async function assertProjectRoot(projectRoot) {
  const requested = path.resolve(projectRoot);
  const resolved = await fs.realpath(requested).catch(() => requested);
  const filesystemRoot = path.parse(resolved).root;
  if (resolved === filesystemRoot || resolved === path.resolve(os.homedir())) {
    throw new DesignomeError(
      'Refusing to use a broad filesystem or home directory as a target project',
      {
        code: 'UNSAFE_TARGET_PROJECT',
      },
    );
  }
  const stat = await fs.stat(resolved).catch(() => null);
  if (!stat?.isDirectory()) {
    throw new DesignomeError(`Target project is not a directory: ${resolved}`, {
      code: 'TARGET_PROJECT_MISSING',
    });
  }
  const packagePath = path.join(resolved, 'package.json');
  if (!(await pathExists(packagePath))) {
    throw new DesignomeError('Target project is missing package.json', {
      code: 'PROJECT_PACKAGE_JSON_MISSING',
      details: {
        checkedPath: packagePath,
        prerequisite:
          'Designome installation and audit require a JavaScript package root with package.json.',
        resolution:
          'Pass the application package root or create package.json before retrying.',
        writesPerformed: false,
      },
    });
  }
  return resolved;
}

async function assertManagedDirectorySafe(projectRoot) {
  const managedDirectory = path.join(projectRoot, '.designome');
  if (!(await pathExists(managedDirectory))) return;
  const stat = await fs.stat(managedDirectory);
  if (!stat.isDirectory()) {
    throw new DesignomeError('.designome exists but is not a directory', {
      code: 'UNSAFE_MANAGED_DIRECTORY',
    });
  }
  const realManagedDirectory = await fs.realpath(managedDirectory);
  relativeInside(projectRoot, realManagedDirectory, '.designome directory');
}

async function resolveCssEntry(projectRoot, requestedEntry) {
  if (requestedEntry) {
    const candidate = resolveProjectPath(
      projectRoot,
      requestedEntry,
      '--css-entry',
    );
    if (!(await pathExists(candidate))) {
      throw new DesignomeError(`CSS entry does not exist: ${requestedEntry}`, {
        code: 'CSS_ENTRY_MISSING',
      });
    }
    const resolved = await fs.realpath(candidate);
    relativeInside(projectRoot, resolved, '--css-entry');
    const stat = await fs.stat(resolved);
    if (!stat.isFile()) {
      throw new DesignomeError(`CSS entry is not a file: ${requestedEntry}`, {
        code: 'INVALID_CSS_ENTRY',
      });
    }
    return resolved;
  }

  const matches = [];
  for (const candidate of cssCandidates) {
    const candidatePath = path.join(projectRoot, candidate);
    if (await pathExists(candidatePath)) {
      const resolvedCandidate = await fs.realpath(candidatePath);
      relativeInside(projectRoot, resolvedCandidate, 'discovered CSS entry');
      matches.push(resolvedCandidate);
    }
  }
  if (matches.length !== 1) {
    throw new DesignomeError(
      matches.length === 0
        ? 'No supported CSS entry was discovered; pass --css-entry'
        : 'Multiple CSS entries were discovered; pass --css-entry',
      {
        code: 'CSS_ENTRY_AMBIGUOUS',
        details: matches.map((match) =>
          toPosixPath(path.relative(projectRoot, match)),
        ),
      },
    );
  }
  return matches[0];
}

async function discoverInstructionFiles(projectRoot, cssEntryPath) {
  const results = [];
  const relativeDirectory = path.relative(
    projectRoot,
    path.dirname(cssEntryPath),
  );
  const segments =
    relativeDirectory === '' ? [] : relativeDirectory.split(path.sep);
  let current = projectRoot;
  for (const segment of ['', ...segments]) {
    if (segment) current = path.join(current, segment);
    for (const name of ['AGENTS.md', 'CLAUDE.md']) {
      const candidate = path.join(current, name);
      if ((await pathExists(candidate)) && !results.includes(candidate))
        results.push(candidate);
    }
  }
  return results.map((result) =>
    toPosixPath(path.relative(projectRoot, result)),
  );
}

function manifestArtifact(manifest, relativePath, kind) {
  return manifest?.managedArtifacts?.find(
    (artifact) => artifact.path === relativePath && artifact.kind === kind,
  );
}

async function inspectOwnedFile(
  projectRoot,
  relativePath,
  desiredContent,
  previousManifest,
) {
  const absolutePath = path.join(projectRoot, relativePath);
  const current = await readTextIfExists(absolutePath);
  const previous = manifestArtifact(previousManifest, relativePath, 'file');
  if (!previous && current !== null) {
    return {
      path: relativePath,
      kind: 'file',
      action: 'conflict',
      reason: 'Existing file is not owned by the manifest.',
      expectedOwner: 'designome',
      recordedChecksum: null,
      observedChecksum: sha256(current),
      nature: 'unmanaged-file-collision',
      refusedOperations: ['overwrite'],
      safeResolutions: [
        'Move or rename the unmanaged file after review.',
        'Choose a different Designome installation path.',
      ],
    };
  }
  if (previous && current === null) {
    return {
      path: relativePath,
      kind: 'file',
      action: 'conflict',
      reason: 'Previously managed file is missing.',
      expectedOwner: 'designome',
      recordedChecksum: previous.sha256,
      observedChecksum: null,
      nature: 'managed-file-missing',
      refusedOperations: ['overwrite', 'delete'],
      safeResolutions: [
        'Restore the manifest-owned file from version control.',
        'Perform an explicit ownership migration before reinstalling.',
      ],
    };
  }
  if (previous && sha256(current) !== previous.sha256) {
    return {
      path: relativePath,
      kind: 'file',
      action: 'conflict',
      reason: 'Managed file was modified outside Designome.',
      expectedOwner: 'designome',
      recordedChecksum: previous.sha256,
      observedChecksum: sha256(current),
      nature: 'managed-file-modified',
      refusedOperations: ['overwrite', 'delete'],
      safeResolutions: [
        'Move intentional changes to a user-owned override and restore the managed file.',
        'Review and explicitly migrate ownership before reinstalling.',
      ],
    };
  }
  return {
    path: relativePath,
    kind: 'file',
    action:
      current === null
        ? 'create'
        : current === desiredContent
          ? 'unchanged'
          : 'update',
    content: desiredContent,
    sha256: sha256(desiredContent),
    observedChecksum: current === null ? null : sha256(current),
  };
}

async function inspectObsoleteDocumentationFiles({
  projectRoot,
  previousManifest,
  documentationRelative,
  desiredPaths,
}) {
  if (!previousManifest) return [];
  const previousDirectory =
    previousManifest.adapter?.documentationDirectory ?? documentationRelative;
  const prefix = `${previousDirectory.replace(/\/$/u, '')}/`;
  const obsolete = (previousManifest.managedArtifacts ?? []).filter(
    (artifact) =>
      artifact.kind === 'file' &&
      artifact.path.startsWith(prefix) &&
      !desiredPaths.has(artifact.path),
  );
  const actions = [];
  for (const artifact of obsolete) {
    const absolutePath = resolveProjectPath(
      projectRoot,
      artifact.path,
      'obsolete documentation path',
    );
    const current = await readTextIfExists(absolutePath);
    if (current === null) {
      actions.push({
        path: artifact.path,
        kind: 'file',
        action: 'conflict',
        reason: 'Previously managed documentation file is missing.',
        expectedOwner: 'designome',
        recordedChecksum: artifact.sha256,
        observedChecksum: null,
        nature: 'managed-file-missing',
        refusedOperations: ['delete', 'overwrite'],
        safeResolutions: [
          'Restore the managed file before retrying the migration.',
          'Review an explicit ownership migration.',
        ],
      });
    } else if (sha256(current) !== artifact.sha256) {
      actions.push({
        path: artifact.path,
        kind: 'file',
        action: 'conflict',
        reason: 'Managed documentation file was modified outside Designome.',
        expectedOwner: 'designome',
        recordedChecksum: artifact.sha256,
        observedChecksum: sha256(current),
        nature: 'managed-file-modified',
        refusedOperations: ['delete', 'overwrite'],
        safeResolutions: [
          'Move intentional changes to user-owned documentation and restore the managed file.',
          'Review an explicit ownership migration.',
        ],
      });
    } else {
      actions.push({
        path: artifact.path,
        kind: 'file',
        action: 'delete',
        observedChecksum: sha256(current),
      });
    }
  }
  return actions;
}

async function inspectBlockFile({
  projectRoot,
  relativePath,
  desiredBlock,
  startMarker,
  endMarker,
  placement,
  previousManifest,
}) {
  const absolutePath = path.join(projectRoot, relativePath);
  const current = (await readTextIfExists(absolutePath)) ?? '';
  const inspection = inspectManagedBlock(current, startMarker, endMarker);
  const previous = manifestArtifact(previousManifest, relativePath, 'block');

  if (!previous && (inspection.startCount !== 0 || inspection.endCount !== 0)) {
    return {
      path: relativePath,
      kind: 'block',
      action: 'conflict',
      reason: 'Existing managed markers are not owned by the manifest.',
      expectedOwner: 'designome',
      recordedChecksum: null,
      observedChecksum: inspection.block ? sha256(inspection.block) : null,
      nature: 'unmanaged-marker-collision',
      refusedOperations: ['overwrite'],
      safeResolutions: [
        'Remove or rename the unmanaged markers after review.',
        'Adopt the block only through an explicit ownership migration.',
      ],
    };
  }
  if (previous) {
    if (
      inspection.startCount !== 1 ||
      inspection.endCount !== 1 ||
      inspection.block === null
    ) {
      return {
        path: relativePath,
        kind: 'block',
        action: 'conflict',
        reason: 'Managed markers are missing or duplicated.',
        expectedOwner: 'designome',
        recordedChecksum: previous.sha256,
        observedChecksum: inspection.block ? sha256(inspection.block) : null,
        nature: 'managed-marker-structure-changed',
        refusedOperations: ['overwrite'],
        safeResolutions: [
          'Restore exactly one manifest-owned marker block.',
          'Review an explicit ownership migration.',
        ],
      };
    }
    if (sha256(inspection.block) !== previous.sha256) {
      return {
        path: relativePath,
        kind: 'block',
        action: 'conflict',
        reason: 'Managed block was modified outside Designome.',
        expectedOwner: 'designome',
        recordedChecksum: previous.sha256,
        observedChecksum: sha256(inspection.block),
        nature: 'managed-block-modified',
        refusedOperations: ['overwrite'],
        safeResolutions: [
          'Move intentional changes outside the managed block and restore it.',
          'Review an explicit ownership migration.',
        ],
      };
    }
  }

  let desiredContent;
  try {
    desiredContent = upsertManagedBlock(
      current,
      desiredBlock,
      startMarker,
      endMarker,
      { placement },
    );
  } catch (error) {
    return {
      path: relativePath,
      kind: 'block',
      action: 'conflict',
      reason: error.message,
      expectedOwner: 'designome',
      recordedChecksum: previous?.sha256 ?? null,
      observedChecksum: inspection.block ? sha256(inspection.block) : null,
      nature: 'managed-block-invalid',
      refusedOperations: ['overwrite'],
      safeResolutions: ['Repair the marker structure and retry the dry-run.'],
    };
  }
  return {
    path: relativePath,
    kind: 'block',
    action:
      current === ''
        ? 'create'
        : current === desiredContent
          ? 'unchanged'
          : 'update',
    content: desiredContent,
    blockSha256: sha256(desiredBlock),
    startMarker,
    endMarker,
    observedChecksum: current === '' ? null : sha256(current),
  };
}

function publicAction(action) {
  const {
    content,
    blockSha256,
    startMarker,
    endMarker,
    sha256: contentSha,
    ...safe
  } = action;
  return safe;
}

async function removeEmptyParents(projectRoot, absolutePath) {
  let current = path.dirname(absolutePath);
  while (
    current !== projectRoot &&
    current.startsWith(`${projectRoot}${path.sep}`)
  ) {
    const entries = await fs.readdir(current).catch(() => null);
    if (!entries || entries.length > 0) break;
    await fs.rmdir(current).catch(() => {});
    current = path.dirname(current);
  }
}

async function writeTransactionJournal(projectRoot, journal) {
  await atomicWrite(
    path.join(projectRoot, transactionRelativePath),
    jsonText(journal),
  );
}

async function rollbackTransaction(projectRoot, journal) {
  const rollbackErrors = [];
  for (const backup of [...journal.backups].reverse()) {
    let absolutePath;
    try {
      if (
        typeof backup.path !== 'string' ||
        (backup.content !== null && typeof backup.content !== 'string')
      ) {
        throw new Error('Transaction backup entry is invalid');
      }
      absolutePath = resolveProjectPath(
        projectRoot,
        backup.path,
        'transaction backup path',
      );
      if (backup.content === null) {
        await fs.rm(absolutePath, { force: true });
        await removeEmptyParents(projectRoot, absolutePath);
      } else {
        await atomicWrite(absolutePath, backup.content);
      }
    } catch (error) {
      rollbackErrors.push(`${backup.path}: ${error.message}`);
    }
  }
  if (rollbackErrors.length > 0) {
    throw new DesignomeError('Installation rollback was incomplete', {
      code: 'INSTALLATION_ROLLBACK_FAILED',
      details: rollbackErrors,
    });
  }
}

export async function recoverInterruptedInstallation({ projectPath }) {
  const projectRoot = await assertProjectRoot(projectPath);
  const journalPath = path.join(projectRoot, transactionRelativePath);
  if (!(await pathExists(journalPath))) {
    return { status: 'not-required', recovered: false };
  }
  let journal;
  try {
    journal = await readJson(journalPath);
  } catch (error) {
    throw new DesignomeError('Interrupted installation journal is unreadable', {
      code: 'INSTALLATION_JOURNAL_UNREADABLE',
      details: [error.message],
    });
  }
  if (journal.schemaVersion !== '1.0.0' || !Array.isArray(journal.backups)) {
    throw new DesignomeError(
      'Interrupted installation journal is incompatible',
      {
        code: 'INSTALLATION_JOURNAL_INCOMPATIBLE',
        details: { schemaVersion: journal.schemaVersion ?? null },
      },
    );
  }
  if (journal.owner !== 'designome') {
    throw new DesignomeError(
      'Interrupted installation journal owner is invalid',
      {
        code: 'INSTALLATION_JOURNAL_INCOMPATIBLE',
        details: { owner: journal.owner ?? null },
      },
    );
  }
  await rollbackTransaction(projectRoot, journal);
  await fs.rm(journalPath, { force: true });
  await removeEmptyParents(projectRoot, journalPath);
  return {
    status: 'recovered',
    recovered: true,
    transactionId: journal.transactionId,
    restoredArtifactCount: journal.backups.length,
  };
}

async function prepareInstallation(plan, writeActions, transactionId) {
  const stagingDirectory = await fs.mkdtemp(
    path.join(os.tmpdir(), `designome-install-${transactionId}-`),
  );
  const prepared = [];
  try {
    for (const [index, action] of writeActions.entries()) {
      if (action.action === 'delete') {
        prepared.push({ ...action, stagedPath: null });
        continue;
      }
      const stagedPath = path.join(stagingDirectory, String(index));
      await atomicWrite(stagedPath, action.content);
      const stagedContent = await fs.readFile(stagedPath, 'utf8');
      if (stagedContent !== action.content) {
        throw new DesignomeError(
          'Prepared installation artifact failed validation',
          {
            code: 'INSTALLATION_PREPARATION_INVALID',
            details: { path: action.path },
          },
        );
      }
      prepared.push({ ...action, stagedPath });
    }
    return { stagingDirectory, prepared };
  } catch (error) {
    await fs.rm(stagingDirectory, { force: true, recursive: true });
    throw error;
  }
}

async function assertPlanStillCurrent(projectRoot, action) {
  const absolutePath = path.join(projectRoot, action.path);
  const current = await readTextIfExists(absolutePath);
  const observed = current === null ? null : sha256(current);
  if (observed !== (action.observedChecksum ?? null)) {
    throw new DesignomeError('Target changed after installation planning', {
      code: 'INSTALLATION_PLAN_STALE',
      details: {
        path: action.path,
        plannedChecksum: action.observedChecksum ?? null,
        observedChecksum: observed,
        refusedOperations: [action.action],
        resolution: 'Run a new diagnostic and dry-run before retrying.',
      },
    });
  }
}

async function verifyAppliedActions(projectRoot, actions) {
  const errors = [];
  for (const action of actions) {
    const absolutePath = path.join(projectRoot, action.path);
    const current = await readTextIfExists(absolutePath);
    if (action.action === 'delete') {
      if (current !== null) errors.push(`${action.path} was not deleted`);
    } else if (current !== action.content) {
      errors.push(`${action.path} does not match its prepared content`);
    }
  }
  if (errors.length > 0) {
    throw new DesignomeError(
      'Applied installation files failed validation before manifest commit',
      {
        code: 'INSTALLATION_APPLY_VERIFICATION_FAILED',
        details: errors,
      },
    );
  }
}

export async function planInstallation({
  dnaPath,
  projectPath,
  cssEntry,
  scope = ':root',
  documentationDirectory = defaultDocumentationDirectory,
  rulePrecedence = 'complement',
  existingRulePaths = [],
  stylingStrategy = 'auto',
  uiKitPreference = 'auto',
  instructionsReviewed = false,
}) {
  if (![':root', '[data-designome]'].includes(scope)) {
    throw new DesignomeError(
      'CSS scope must be either :root or [data-designome]',
      { code: 'INVALID_CSS_SCOPE' },
    );
  }
  if (
    !['complement', 'existing-first', 'designome-first'].includes(
      rulePrecedence,
    )
  ) {
    throw new DesignomeError(
      'Rule precedence must be complement, existing-first, or designome-first',
      {
        code: 'INVALID_RULE_PRECEDENCE',
      },
    );
  }
  if (!['auto', 'none', 'shadcn'].includes(uiKitPreference)) {
    throw new DesignomeError(
      'UI kit preference must be auto, none, or shadcn',
      { code: 'INVALID_UI_KIT_PREFERENCE' },
    );
  }
  if (
    ![
      'auto',
      'css-variables',
      'tailwind-utilities',
      'shadcn-components',
    ].includes(stylingStrategy)
  ) {
    throw new DesignomeError(
      'Styling strategy must be auto, css-variables, tailwind-utilities, or shadcn-components',
      {
        code: 'INVALID_STYLE_STRATEGY',
      },
    );
  }

  const projectRoot = await assertProjectRoot(projectPath);
  await assertManagedDirectorySafe(projectRoot);
  const resolvedDnaPath = path.resolve(dnaPath);
  const dna = await readJson(resolvedDnaPath).catch((error) => {
    throw new DesignomeError(`Cannot read Design DNA: ${resolvedDnaPath}`, {
      code: 'DESIGN_DNA_UNREADABLE',
      details: [error.message],
    });
  });
  await assertValidDesignDna(dna, { requireAccepted: true });
  const conceptMatrix = await readJson(
    path.join(pluginRoot, 'concepts', 'concept-matrix.v0.2.json'),
  );

  const resolvedCssEntry = await resolveCssEntry(projectRoot, cssEntry);
  const cssEntryRelative = toPosixPath(
    relativeInside(projectRoot, resolvedCssEntry, 'CSS entry'),
  );
  const cssDirectory = path.dirname(resolvedCssEntry);
  const resolvedDocumentationDirectory = resolveProjectPath(
    projectRoot,
    documentationDirectory,
    '--docs-dir',
  );
  const documentationRelative = toPosixPath(
    relativeInside(projectRoot, resolvedDocumentationDirectory, '--docs-dir'),
  );
  if (
    !documentationRelative ||
    documentationRelative === '.' ||
    documentationRelative.startsWith('.designome')
  ) {
    throw new DesignomeError(
      'Documentation directory must be a visible project-relative directory outside .designome',
      {
        code: 'INVALID_DOCUMENTATION_DIRECTORY',
      },
    );
  }
  const normalizedExistingRulePaths = [];
  for (const rulePath of existingRulePaths) {
    const absoluteRulePath = resolveProjectPath(
      projectRoot,
      rulePath,
      '--existing-rules',
    );
    if (!(await pathExists(absoluteRulePath))) {
      throw new DesignomeError(
        `Declared existing rule path does not exist: ${rulePath}`,
        {
          code: 'EXISTING_RULE_PATH_MISSING',
        },
      );
    }
    normalizedExistingRulePaths.push(
      toPosixPath(
        relativeInside(
          projectRoot,
          await fs.realpath(absoluteRulePath),
          '--existing-rules',
        ),
      ),
    );
  }
  const styling = await detectStylingContext(
    projectRoot,
    resolvedCssEntry,
    stylingStrategy,
    uiKitPreference,
  );
  const integrationPolicy = {
    documentationLayout: 'complete-v1',
    rulePrecedence,
    existingRulePaths: [...new Set(normalizedExistingRulePaths)].sort(),
    uiKitPreference,
  };
  const generatedCssPath = path.join(cssDirectory, 'designome.generated.css');
  const overridesCssPath = path.join(cssDirectory, 'designome.overrides.css');
  if (
    resolvedCssEntry === generatedCssPath ||
    resolvedCssEntry === overridesCssPath
  ) {
    throw new DesignomeError(
      'The CSS entry cannot be a Designome-managed CSS file',
      {
        code: 'INVALID_CSS_ENTRY',
      },
    );
  }

  const generatedCssRelative = toPosixPath(
    relativeInside(projectRoot, generatedCssPath),
  );
  const overridesCssRelative = toPosixPath(
    relativeInside(projectRoot, overridesCssPath),
  );
  const agentsRelative = 'AGENTS.md';
  const manifestPath = path.join(projectRoot, manifestRelativePath);
  const previousManifest = (await pathExists(manifestPath))
    ? await readJson(manifestPath)
    : null;
  if (
    previousManifest &&
    !supportedManifestVersions.has(previousManifest.schemaVersion)
  ) {
    throw new DesignomeError('Installed manifest version is unsupported', {
      code: 'UNSUPPORTED_MANIFEST',
    });
  }

  const generatedCss = renderGeneratedCss(dna, scope, styling);
  const dnaText = jsonText(dna);
  const importBlock = renderCssImportBlock(
    path.basename(generatedCssPath),
    path.basename(overridesCssPath),
  );
  const guidanceBlock = renderGuidanceBlock({
    documentationDirectory: documentationRelative,
    integrationPolicy,
    styling,
  });
  const documentation = renderDocumentation({
    dna,
    styling,
    integrationPolicy,
    documentationDirectory: documentationRelative,
    matrix: conceptMatrix,
  });
  const auditSkill = new Map([
    [
      'SKILL.md',
      await fs.readFile(
        path.join(pluginRoot, 'skills', 'designome-audit', 'SKILL.md'),
        'utf8',
      ),
    ],
    [
      'agents/openai.yaml',
      await fs.readFile(
        path.join(
          pluginRoot,
          'skills',
          'designome-audit',
          'agents',
          'openai.yaml',
        ),
        'utf8',
      ),
    ],
    [
      'contract.json',
      await fs.readFile(
        path.join(pluginRoot, 'skills', 'designome-audit', 'contract.json'),
        'utf8',
      ),
    ],
  ]);
  const instructionFiles = await discoverInstructionFiles(
    projectRoot,
    resolvedCssEntry,
  );

  const actions = [];
  actions.push(
    await inspectOwnedFile(
      projectRoot,
      installedDnaRelativePath,
      dnaText,
      previousManifest,
    ),
  );
  for (const [filename, content] of documentation) {
    actions.push(
      await inspectOwnedFile(
        projectRoot,
        toPosixPath(path.join(documentationRelative, filename)),
        content,
        previousManifest,
      ),
    );
  }
  const desiredDocumentationPaths = new Set(
    [...documentation.keys()].map((filename) =>
      toPosixPath(path.join(documentationRelative, filename)),
    ),
  );
  actions.push(
    ...(await inspectObsoleteDocumentationFiles({
      projectRoot,
      previousManifest,
      documentationRelative,
      desiredPaths: desiredDocumentationPaths,
    })),
  );
  for (const [filename, content] of auditSkill) {
    actions.push(
      await inspectOwnedFile(
        projectRoot,
        toPosixPath(path.join(auditSkillRelativeDirectory, filename)),
        content,
        previousManifest,
      ),
    );
  }
  actions.push(
    await inspectOwnedFile(
      projectRoot,
      generatedCssRelative,
      generatedCss,
      previousManifest,
    ),
  );
  actions.push(
    await inspectBlockFile({
      projectRoot,
      relativePath: cssEntryRelative,
      desiredBlock: importBlock,
      startMarker: cssStartMarker,
      endMarker: cssEndMarker,
      placement: 'css-top',
      previousManifest,
    }),
  );
  actions.push(
    await inspectBlockFile({
      projectRoot,
      relativePath: agentsRelative,
      desiredBlock: guidanceBlock,
      startMarker: guidanceStartMarker,
      endMarker: guidanceEndMarker,
      placement: 'append',
      previousManifest,
    }),
  );

  const overridesCurrent = await readTextIfExists(overridesCssPath);
  actions.push({
    path: overridesCssRelative,
    kind: 'user-owned',
    action: overridesCurrent === null ? 'create' : 'preserve',
    content: overridesCurrent === null ? renderOverridesCss() : null,
    observedChecksum:
      overridesCurrent === null ? null : sha256(overridesCurrent),
  });
  const auditConfigPath = path.join(projectRoot, auditConfigRelativePath);
  const auditConfigCurrent = await readTextIfExists(auditConfigPath);
  actions.push({
    path: auditConfigRelativePath,
    kind: 'user-owned',
    action: auditConfigCurrent === null ? 'create' : 'preserve',
    content: auditConfigCurrent === null ? renderAuditConfig() : null,
    observedChecksum:
      auditConfigCurrent === null ? null : sha256(auditConfigCurrent),
  });

  const conflicts = actions.filter((action) => action.action === 'conflict');
  const packageJson = await readJson(path.join(pluginRoot, 'package.json'));
  const dnaHash = sha256(dnaText);
  const configurationFingerprint = sha256(
    jsonText({
      dnaHash,
      cssEntryRelative,
      generatedCssRelative,
      overridesCssRelative,
      scope,
      documentationRelative,
      documentationLayoutVersion: conceptMatrix.documentationLayoutVersion,
      integrationPolicy,
      styling,
    }),
  );
  const installedAt =
    previousManifest?.configurationFingerprint === configurationFingerprint
      ? previousManifest.installedAt
      : new Date().toISOString();

  const managedArtifacts = actions
    .filter((action) => action.kind === 'file' || action.kind === 'block')
    .filter(
      (action) => action.action !== 'conflict' && action.action !== 'delete',
    )
    .map((action) =>
      action.kind === 'file'
        ? { path: action.path, kind: 'file', sha256: action.sha256 }
        : {
            path: action.path,
            kind: 'block',
            sha256: action.blockSha256,
            startMarker: action.startMarker,
            endMarker: action.endMarker,
          },
    );
  const manifest = {
    schemaVersion: '0.2.0',
    pluginVersion: packageJson.version,
    installedAt,
    configurationFingerprint,
    dna: {
      documentId: dna.documentId,
      revision: dna.revision.number,
      sha256: dnaHash,
    },
    adapter: {
      cssEntry: cssEntryRelative,
      generatedCss: generatedCssRelative,
      overridesCss: overridesCssRelative,
      scope,
      documentationDirectory: documentationRelative,
      documentationLayoutVersion: conceptMatrix.documentationLayoutVersion,
      styling,
      integrationPolicy,
      instructionFiles,
      instructionsReviewed:
        instructionsReviewed ||
        previousManifest?.adapter?.instructionsReviewed === true,
    },
    managedArtifacts,
    userOwnedArtifacts: [
      { path: overridesCssRelative, kind: 'file', rewritePolicy: 'preserve' },
      {
        path: auditConfigRelativePath,
        kind: 'file',
        rewritePolicy: 'preserve',
      },
    ],
  };
  const manifestText = jsonText(manifest);
  const currentManifestText = await readTextIfExists(manifestPath);
  const manifestAction = {
    path: manifestRelativePath,
    kind: 'manifest',
    action:
      conflicts.length > 0
        ? 'blocked'
        : currentManifestText === null
          ? 'create'
          : currentManifestText === manifestText
            ? 'unchanged'
            : 'update',
    content: manifestText,
    observedChecksum:
      currentManifestText === null ? null : sha256(currentManifestText),
  };
  actions.push(manifestAction);

  return {
    status: conflicts.length > 0 ? 'conflict' : 'ready',
    projectRoot,
    dnaPath: resolvedDnaPath,
    dna,
    manifest,
    actions,
    publicPlan: {
      status: conflicts.length > 0 ? 'conflict' : 'ready',
      dna: manifest.dna,
      adapter: manifest.adapter,
      actions: actions.map(publicAction),
      conflictCount: conflicts.length,
      transaction: {
        schemaVersion: '1.0.0',
        phases: [
          'diagnostic',
          'preflight',
          'plan',
          'prepare',
          'validate-prepared',
          'apply',
          'verify',
          'commit-manifest',
          'cleanup',
        ],
        manifestWrittenLast: true,
        rollbackOnFailure: true,
      },
    },
  };
}

export async function installDesignDna(options) {
  const transactionPath = path.join(
    path.resolve(options.projectPath),
    transactionRelativePath,
  );
  const recovery = options.dryRun
    ? {
        status: (await pathExists(transactionPath))
          ? 'recovery-required'
          : 'not-required',
        recovered: false,
        readOnly: true,
      }
    : await recoverInterruptedInstallation({
        projectPath: options.projectPath,
      });
  const plan = await planInstallation(options);
  if (plan.status === 'conflict' || options.dryRun) {
    return { ...plan.publicPlan, recovery };
  }
  if (!options.instructionsReviewed) {
    throw new DesignomeError(
      'Writing requires --instructions-reviewed after the dry-run and instruction review',
      {
        code: 'INSTRUCTIONS_NOT_REVIEWED',
      },
    );
  }

  const writeActions = plan.actions.filter((action) =>
    ['create', 'update', 'delete'].includes(action.action),
  );
  const transactionId = randomUUID();
  let prepared;
  try {
    if (options.failureInjection === 'prepare') {
      throw new Error('Injected preparation failure');
    }
    prepared = await prepareInstallation(plan, writeActions, transactionId);
  } catch (error) {
    throw new DesignomeError(
      'Installation preparation failed before target writes',
      {
        code: 'INSTALLATION_PREPARATION_FAILED',
        details: {
          cause: error.message,
          projectModified: false,
          transactionId,
        },
      },
    );
  }

  const journal = {
    schemaVersion: '1.0.0',
    transactionId,
    owner: 'designome',
    projectRoot: plan.projectRoot,
    createdAt: new Date().toISOString(),
    status: 'applying',
    currentAction: null,
    backups: [],
  };
  try {
    await writeTransactionJournal(plan.projectRoot, journal);
    const appliedBeforeManifest = [];
    for (const [index, action] of prepared.prepared.entries()) {
      const absolutePath = path.join(plan.projectRoot, action.path);
      if (action.kind === 'manifest') {
        journal.status = 'verifying-before-manifest';
        await writeTransactionJournal(plan.projectRoot, journal);
        await verifyAppliedActions(plan.projectRoot, appliedBeforeManifest);
        journal.status = 'committing-manifest';
        await writeTransactionJournal(plan.projectRoot, journal);
      }
      await assertPlanStillCurrent(plan.projectRoot, action);
      journal.currentAction = action.path;
      journal.backups.push({
        path: action.path,
        content: await readTextIfExists(absolutePath),
      });
      await writeTransactionJournal(plan.projectRoot, journal);
      if (options.failureInjection === 'apply' && index === 1) {
        throw new Error('Injected application failure');
      }
      if (action.action === 'delete') {
        await fs.rm(absolutePath, { force: true });
      } else {
        await atomicWrite(
          absolutePath,
          await fs.readFile(action.stagedPath, 'utf8'),
        );
      }
      if (action.kind !== 'manifest') appliedBeforeManifest.push(action);
    }
  } catch (error) {
    await rollbackTransaction(plan.projectRoot, journal);
    await fs.rm(path.join(plan.projectRoot, transactionRelativePath), {
      force: true,
    });
    await removeEmptyParents(
      plan.projectRoot,
      path.join(plan.projectRoot, transactionRelativePath),
    );
    throw new DesignomeError(
      'Installation failed and completed writes were rolled back',
      {
        code: 'INSTALLATION_ROLLED_BACK',
        details: {
          cause: error.message,
          transactionId,
          rollback: 'completed',
          projectModified: false,
        },
      },
    );
  } finally {
    await fs.rm(prepared.stagingDirectory, { force: true, recursive: true });
  }

  const verification = await verifyInstallation({
    projectPath: plan.projectRoot,
  });
  if (!verification.valid) {
    await rollbackTransaction(plan.projectRoot, journal);
    await fs.rm(path.join(plan.projectRoot, transactionRelativePath), {
      force: true,
    });
    await removeEmptyParents(
      plan.projectRoot,
      path.join(plan.projectRoot, transactionRelativePath),
    );
    throw new DesignomeError(
      'Post-install verification failed and installation was rolled back',
      {
        code: 'POST_INSTALL_VERIFICATION_FAILED',
        details: {
          verificationErrors: verification.errors,
          transactionId,
          rollback: 'completed',
          projectModified: false,
        },
      },
    );
  }

  await fs.rm(path.join(plan.projectRoot, transactionRelativePath), {
    force: true,
  });

  return {
    ...plan.publicPlan,
    status: 'installed',
    verification: 'passed',
    recovery,
    transaction: {
      ...plan.publicPlan.transaction,
      transactionId,
      status: 'committed',
      preparedArtifactCount: writeActions.length,
      appliedArtifactCount: writeActions.length,
      rollback: 'not-required',
    },
  };
}

export async function verifyInstallation({ projectPath }) {
  const projectRoot = await assertProjectRoot(projectPath);
  await assertManagedDirectorySafe(projectRoot);
  const errors = [];
  const manifestPath = path.join(projectRoot, manifestRelativePath);
  if (!(await pathExists(manifestPath))) {
    return {
      valid: false,
      projectRoot,
      errors: ['.designome/manifest.json is missing'],
    };
  }

  let manifest;
  try {
    manifest = await readJson(manifestPath);
  } catch (error) {
    return {
      valid: false,
      projectRoot,
      errors: [`Cannot parse manifest: ${error.message}`],
    };
  }
  if (!supportedManifestVersions.has(manifest.schemaVersion))
    errors.push('Unsupported manifest schemaVersion');

  for (const artifact of manifest.managedArtifacts ?? []) {
    let absolutePath;
    try {
      absolutePath = resolveProjectPath(
        projectRoot,
        artifact.path,
        'managed artifact path',
      );
    } catch (error) {
      errors.push(`Unsafe managed artifact path: ${String(artifact.path)}`);
      continue;
    }
    const content = await readTextIfExists(absolutePath);
    if (content === null) {
      errors.push(`Managed artifact is missing: ${artifact.path}`);
      continue;
    }
    if (artifact.kind === 'file') {
      if (sha256(content) !== artifact.sha256)
        errors.push(`Managed file checksum mismatch: ${artifact.path}`);
      continue;
    }
    if (artifact.kind === 'block') {
      const block = inspectManagedBlock(
        content,
        artifact.startMarker,
        artifact.endMarker,
      );
      if (
        block.startCount !== 1 ||
        block.endCount !== 1 ||
        block.block === null
      ) {
        errors.push(
          `Managed block markers are missing or duplicated: ${artifact.path}`,
        );
      } else if (sha256(block.block) !== artifact.sha256) {
        errors.push(`Managed block checksum mismatch: ${artifact.path}`);
      }
    }
  }

  for (const artifact of manifest.userOwnedArtifacts ?? []) {
    let absolutePath;
    try {
      absolutePath = resolveProjectPath(
        projectRoot,
        artifact.path,
        'user-owned artifact path',
      );
    } catch (error) {
      errors.push(`Unsafe user-owned artifact path: ${String(artifact.path)}`);
      continue;
    }
    if (!(await pathExists(absolutePath))) {
      errors.push(`User-owned override artifact is missing: ${artifact.path}`);
    }
  }

  const installedDnaPath = path.join(projectRoot, installedDnaRelativePath);
  if (await pathExists(installedDnaPath)) {
    try {
      const dna = await readJson(installedDnaPath);
      errors.push(
        ...(await validateDesignDna(dna, { requireAccepted: true })).map(
          (error) => `Design DNA: ${error}`,
        ),
      );
      if (sha256(jsonText(dna)) !== manifest.dna?.sha256)
        errors.push('Installed Design DNA does not match manifest DNA hash');
    } catch (error) {
      errors.push(`Cannot validate installed Design DNA: ${error.message}`);
    }
  }

  return {
    valid: errors.length === 0,
    projectRoot,
    documentId: manifest.dna?.documentId ?? null,
    revision: manifest.dna?.revision ?? null,
    managedArtifactCount: manifest.managedArtifacts?.length ?? 0,
    errors,
  };
}
