import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { assertValidDesignDna, validateDesignDna } from './design-dna.mjs';
import { DesignomeError } from './errors.mjs';
import {
  atomicWrite,
  jsonText,
  pathExists,
  pluginRoot,
  readJson,
  readTextIfExists,
  relativeInside,
  resolveProjectPath,
  rollbackWrites,
  sha256,
  toPosixPath,
} from './files.mjs';
import { inspectManagedBlock, upsertManagedBlock } from './markers.mjs';

const manifestRelativePath = '.designome/manifest.json';
const installedDnaRelativePath = '.designome/design-dna.json';
const auditConfigRelativePath = '.designome/audit.config.json';
const defaultDocumentationDirectory = 'docs/designome';
const auditSkillRelativeDirectory = '.agents/skills/designome-audit';
const supportedManifestVersions = new Set(['0.1.0', '0.2.0']);
const cssStartMarker = '/* designome:generated-import:start */';
const cssEndMarker = '/* designome:generated-import:end */';
const guidanceStartMarker = '<!-- designome:guidance:start -->';
const guidanceEndMarker = '<!-- designome:guidance:end -->';

const cssCandidates = [
  'src/app/globals.css',
  'app/globals.css',
  'src/styles/globals.css',
  'styles/globals.css',
  'src/index.css',
  'src/main.css',
];

function safeCssComment(value) {
  return String(value)
    .replace(/\*\//gu, '* /')
    .replace(/[\r\n]+/gu, ' ');
}

function cssName(tokenId) {
  return tokenId
    .replace(/^token\./u, '')
    .replace(/[^a-zA-Z0-9-]+/gu, '-')
    .replace(/-+/gu, '-')
    .replace(/^-|-$/gu, '')
    .toLowerCase();
}

function cssValue(value, tokenId) {
  const rendered = String(value);
  if (
    /[;{}\r\n]/u.test(rendered) ||
    rendered.includes('/*') ||
    rendered.includes('*/')
  ) {
    throw new DesignomeError(`Unsafe literal CSS value in ${tokenId}`, {
      code: 'UNSAFE_CSS_TOKEN',
    });
  }
  return rendered;
}

function renderGeneratedCss(dna, scope, styling) {
  const exactTokens = [];
  const nonLiteralTokens = [];
  const generatedNames = new Set();
  for (const token of dna.tokens) {
    const generatedName = cssName(token.id);
    if (generatedNames.has(generatedName)) {
      throw new DesignomeError(`CSS token name collision for ${token.id}`, {
        code: 'CSS_TOKEN_COLLISION',
      });
    }
    generatedNames.add(generatedName);
    if (token.value?.kind === 'exact') {
      exactTokens.push(
        `    --designome-${generatedName}: ${cssValue(token.value.value, token.id)};`,
      );
    } else if (
      token.value?.kind === 'range' &&
      token.value.strategy === 'bounded' &&
      Number.isFinite(token.value.preferred)
    ) {
      exactTokens.push(
        `    --designome-${generatedName}: ${cssValue(`${token.value.preferred}${token.value.unit}`, token.id)};`,
      );
      nonLiteralTokens.push(
        `  /* ${safeCssComment(token.id)} bounds: ${token.value.minimum} to ${token.value.maximum} ${safeCssComment(token.value.unit)} */`,
      );
    } else {
      const explanation =
        token.value?.expression ??
        token.value?.reason ??
        (token.value?.kind === 'range'
          ? `${token.value.minimum} to ${token.value.maximum} ${token.value.unit}`
          : 'No literal CSS value is available.');
      nonLiteralTokens.push(
        `  /* ${safeCssComment(token.id)}: ${safeCssComment(explanation)} */`,
      );
    }
  }

  const lines = [
    `/* Generated by Designome from ${safeCssComment(dna.documentId)} revision ${dna.revision.number}. */`,
    '/* Do not edit this file. Put project-owned changes in designome.overrides.css. */',
    `/* Styling adapter: ${safeCssComment(styling.strategy)} (${safeCssComment(styling.system)} detected). */`,
    '',
    '@layer designome.tokens {',
    `  ${scope} {`,
    ...(exactTokens.length > 0
      ? exactTokens
      : ['    /* No exact token values were accepted. */']),
    '  }',
    ...(nonLiteralTokens.length > 0 ? ['', ...nonLiteralTokens] : []),
    '}',
    '',
  ];
  return lines.join('\n');
}

function renderOverridesCss() {
  return [
    '/* Project-owned Designome overrides. This file is never overwritten. */',
    '@layer designome.overrides {',
    '  /* Add intentional local overrides here. */',
    '}',
    '',
  ].join('\n');
}

function renderAuditConfig() {
  return jsonText({
    schemaVersion: '0.1.0',
    baseUrl: 'http://127.0.0.1:3000',
    outputDirectory: 'audit',
    routes: [
      {
        id: 'overview',
        path: '/',
        viewports: [
          { name: 'desktop', width: 1440, height: 1000 },
          { name: 'mobile', width: 390, height: 844 },
        ],
        flows: ['load the route'],
      },
    ],
  });
}

function renderCssImportBlock(generatedName, overridesName) {
  return [
    cssStartMarker,
    `@import "./${generatedName}";`,
    `@import "./${overridesName}";`,
    cssEndMarker,
    '',
  ].join('\n');
}

function renderGuidanceBlock({
  documentationDirectory,
  integrationPolicy,
  styling,
}) {
  const existingRules = integrationPolicy.existingRulePaths.length
    ? integrationPolicy.existingRulePaths
        .map((item) => `\`${item}\``)
        .join(', ')
    : 'none declared';
  const stylingInstruction =
    styling.system === 'shadcn'
      ? 'Prefer installed shadcn/ui components, semantic theme tokens, configured aliases, and the declared icon library. Do not reinitialize or overwrite components without explicit approval.'
      : styling.system === 'tailwind'
        ? "Prefer the project's existing Tailwind utilities and theme conventions before adding new component CSS."
        : "Prefer the project's existing styling primitives before adding a parallel component system.";
  return [
    guidanceStartMarker,
    '## Designome-generated UI',
    '',
    `Read \`${documentationDirectory}/README.md\` and \`.designome/design-dna.json\` before generating UI.`,
    `Repository rule precedence is \`${integrationPolicy.rulePrecedence}\`; declared existing UI rules: ${existingRules}.`,
    `The detected styling adapter is \`${styling.strategy}\`. ${stylingInstruction}`,
    'Preserve claim status, cover applicable business states and stress cases, and run `$designome-audit` before delivery.',
    guidanceEndMarker,
    '',
  ].join('\n');
}

function markdownValue(value) {
  if (value?.kind === 'exact') return `Exact: \`${String(value.value)}\``;
  if (value?.kind === 'range')
    return `Range: ${value.minimum}–${value.maximum} ${value.unit}${Number.isFinite(value.preferred) ? `; preferred ${value.preferred} ${value.unit}; strategy \`${value.strategy}\`` : ''}`;
  if (value?.kind === 'relationship') return value.expression;
  return value?.reason ?? 'Unknown';
}

function claimDetails(claim) {
  const evidence = claim.evidenceRefs?.length
    ? claim.evidenceRefs.map((item) => `\`${item}\``).join(', ')
    : 'none; this is not an observed claim';
  const exceptions = claim.exceptions?.length
    ? claim.exceptions.join('; ')
    : 'None documented.';
  return [
    `- Status: \`${claim.epistemicStatus}\``,
    `- Confidence: ${claim.confidence.score} — ${claim.confidence.basis}`,
    `- Scope: ${claim.scope.join(', ')}`,
    `- Evidence: ${evidence}`,
    `- Exceptions: ${exceptions}`,
    `- Validation: ${claim.validation.method}`,
  ].join('\n');
}

function renderTokenDocument(title, introduction, tokens, unknowns = []) {
  const sections = tokens.length
    ? tokens.map((token) =>
        [
          `## ${token.name}`,
          '',
          token.claim.statement,
          '',
          `**Design value:** ${markdownValue(token.value)}`,
          '',
          claimDetails(token.claim),
        ].join('\n'),
      )
    : [
        '## No accepted token',
        '',
        'The accepted Design DNA contains no token in this category. Do not invent one; resolve the relevant unknowns or add an explicitly proposed rule.',
      ].join('\n');
  const unknownSections = unknowns.map((item) =>
    [
      `### ${item.question}`,
      '',
      `- Status: \`unknown\``,
      `- Impact: ${item.impact}`,
      `- Resolution: ${item.resolutionPlan}`,
    ].join('\n'),
  );
  return [
    `# ${title}`,
    '',
    introduction,
    '',
    ...sections,
    ...(unknownSections.length
      ? ['', '## Relevant unknowns', '', ...unknownSections]
      : []),
    '',
  ].join('\n');
}

function renderRulesDocument(dna) {
  const rules = dna.rules.map((rule) =>
    [
      `## ${rule.name}`,
      '',
      `- Rule ID: \`${rule.id}\``,
      `- Strength: \`${rule.strength}\``,
      `- Category: \`${rule.category}\``,
      `- Epistemic status: \`${rule.claim.epistemicStatus}\``,
      '',
      rule.claim.statement,
      '',
      '### Requirements',
      '',
      ...rule.requirements.map((item) => `- ${item}`),
      '',
      '### Validation cases',
      '',
      ...rule.validationCases.map((item) => `- ${item}`),
      '',
      claimDetails(rule.claim),
    ].join('\n'),
  );
  return [
    '# UI rules',
    '',
    `Accepted Design DNA: \`${dna.documentId}\` revision ${dna.revision.number}.`,
    '',
    ...rules,
    '',
  ].join('\n');
}

function renderComponentsDocument(dna) {
  const components = dna.componentPatterns ?? [];
  const componentSections = components.length
    ? components.map((component) =>
        [
          `## ${component.name}`,
          '',
          component.claim.statement,
          '',
          '### Anatomy',
          '',
          ...component.anatomy.map((item) => `- ${item}`),
          '',
          '### Variants',
          '',
          ...component.variants.map((item) => `- ${item}`),
          '',
          '### States',
          '',
          ...component.states.map(
            (item) =>
              `- **${item.name}** — \`${item.status}\`: ${item.behavior}`,
          ),
        ].join('\n'),
      )
    : [
        [
          '## No canonical component catalogue',
          '',
          'The screenshots support reusable rules but not a complete component inventory. Use the rules below without inventing unrequested page or role families.',
          '',
          ...dna.rules
            .filter((rule) =>
              ['layout', 'state', 'interaction'].includes(rule.category),
            )
            .map((rule) => `- \`${rule.id}\` — ${rule.name}`),
        ].join('\n'),
      ];
  return ['# Components and states', '', ...componentSections, ''].join('\n');
}

function renderIntegrationDocument({
  dna,
  styling,
  integrationPolicy,
  documentationDirectory,
}) {
  const evidence = styling.evidence.length
    ? styling.evidence.map((item) => `- ${item}`)
    : ['- No styling-system marker was detected.'];
  const existing = integrationPolicy.existingRulePaths.length
    ? integrationPolicy.existingRulePaths.map((item) => `- \`${item}\``)
    : ['- None declared.'];
  return [
    '# Repository integration',
    '',
    `This project installs \`${dna.documentId}\` revision ${dna.revision.number}. Designome documentation is managed in \`${documentationDirectory}\`.`,
    '',
    '## Styling context',
    '',
    `- Detected system: \`${styling.system}\``,
    `- Integration strategy: \`${styling.strategy}\``,
    `- Detected version: ${styling.version ? `\`${styling.version}\`` : 'unknown'}`,
    ...evidence,
    '',
    styling.system === 'shadcn'
      ? 'Reuse installed shadcn/ui source components and semantic theme tokens first. Respect the configured aliases, React Server Components mode, primitive base, and icon library. Adding or updating components requires a dry-run and explicit authorization; never reinitialize or overwrite a customized component silently.'
      : styling.system === 'tailwind'
        ? 'Use existing Tailwind utilities and theme conventions first. Treat `designome.generated.css` as a namespaced semantic-token bridge, not as permission to build a parallel raw-CSS component system.'
        : 'Use the project styling primitives first. Keep Designome CSS namespaced and avoid creating a parallel component system.',
    '',
    '## Rule precedence',
    '',
    `Policy: \`${integrationPolicy.rulePrecedence}\`.`,
    '',
    integrationPolicy.rulePrecedence === 'complement'
      ? 'Existing repository rules remain authoritative where they speak; Designome fills documented gaps. Contradictions require explicit review.'
      : integrationPolicy.rulePrecedence === 'existing-first'
        ? 'Existing repository rules take precedence. Designome deviations must be recorded in the audit.'
        : 'Accepted Designome rules take precedence for generated UI. Existing-rule conflicts must still be reported and never trigger silent rewrites.',
    '',
    '### Declared existing UI rules',
    '',
    ...existing,
    '',
    'Never mine existing project CSS or components as screenshot evidence. Repository context changes implementation shape, not the meaning or epistemic status of the Design DNA.',
    '',
  ].join('\n');
}

function renderDocumentation({
  dna,
  styling,
  integrationPolicy,
  documentationDirectory,
}) {
  const typographyTokens = dna.tokens.filter(
    (token) => token.category === 'typography',
  );
  const iconTokens = dna.tokens.filter((token) =>
    /icon/iu.test(`${token.id} ${token.name} ${token.claim.statement}`),
  );
  const foundationTokens = dna.tokens.filter(
    (token) => !typographyTokens.includes(token) && !iconTokens.includes(token),
  );
  const iconUnknowns = dna.unknowns.filter((item) =>
    item.conceptRefs.includes('concept.iconographic-coherence'),
  );
  return new Map([
    [
      'README.md',
      [
        '# Designome UI documentation',
        '',
        `Design DNA: \`${dna.documentId}\`, revision ${dna.revision.number}, status \`${dna.status}\`.`,
        '',
        'These files are generated from accepted Design DNA and preserve observed, inferred, proposed, and unknown claims. Read repository integration guidance before applying them.',
        '',
        '- [Visual foundations](./visual-foundations.md)',
        '- [Typography](./typography.md)',
        '- [Iconography](./iconography.md)',
        '- [Components and states](./components-and-states.md)',
        '- [UI rules](./rules.md)',
        '- [Repository integration](./integration.md)',
        '',
      ].join('\n'),
    ],
    [
      'visual-foundations.md',
      renderTokenDocument(
        'Visual foundations',
        'Surface, color, spacing, containment, size, and other perceptual guidance.',
        foundationTokens,
      ),
    ],
    [
      'typography.md',
      renderTokenDocument(
        'Typography',
        'Typography roles and relationships. Exact families or sizes remain unknown unless explicitly evidenced or accepted.',
        typographyTokens,
      ),
    ],
    [
      'iconography.md',
      renderTokenDocument(
        'Iconography',
        'Icon rules describe visual and semantic coherence without inventing an icon library.',
        iconTokens,
        iconUnknowns,
      ),
    ],
    ['components-and-states.md', renderComponentsDocument(dna)],
    ['rules.md', renderRulesDocument(dna)],
    [
      'integration.md',
      renderIntegrationDocument({
        dna,
        styling,
        integrationPolicy,
        documentationDirectory,
      }),
    ],
  ]);
}

async function detectStylingContext(
  projectRoot,
  cssEntryPath,
  requestedStrategy,
) {
  const packagePath = path.join(projectRoot, 'package.json');
  const packageJson = (await pathExists(packagePath))
    ? await readJson(packagePath)
    : {};
  const dependencies = {
    ...(packageJson.dependencies ?? {}),
    ...(packageJson.devDependencies ?? {}),
  };
  const css = (await readTextIfExists(cssEntryPath)) ?? '';
  const shadcnPath = path.join(projectRoot, 'components.json');
  const shadcnConfig = (await pathExists(shadcnPath))
    ? await readJson(shadcnPath)
    : null;
  const tailwindVersion = dependencies.tailwindcss ?? null;
  const tailwindEvidence = [];
  if (tailwindVersion)
    tailwindEvidence.push(
      `package.json declares tailwindcss ${tailwindVersion}`,
    );
  if (dependencies['@tailwindcss/postcss'])
    tailwindEvidence.push('package.json declares @tailwindcss/postcss');
  if (
    /@import\s+["']tailwindcss["']/u.test(css) ||
    /@tailwind\s+(?:base|components|utilities)/u.test(css)
  )
    tailwindEvidence.push('The CSS entry contains a Tailwind directive');
  const detectedSystem = shadcnConfig
    ? 'shadcn'
    : tailwindEvidence.length
      ? 'tailwind'
      : 'css';
  const shadcnEvidence = shadcnConfig
    ? [
        'components.json declares a shadcn/ui project',
        ...(shadcnConfig.tailwind?.cssVariables === true
          ? ['components.json enables CSS-variable theming']
          : []),
      ]
    : [];
  const strategy =
    requestedStrategy === 'auto'
      ? detectedSystem === 'shadcn'
        ? 'shadcn-components'
        : detectedSystem === 'tailwind'
          ? 'tailwind-utilities'
          : 'css-variables'
      : requestedStrategy;
  if (
    strategy === 'tailwind-utilities' &&
    !['tailwind', 'shadcn'].includes(detectedSystem)
  ) {
    throw new DesignomeError(
      'Tailwind strategy was requested but Tailwind was not detected',
      { code: 'STYLE_STRATEGY_UNAVAILABLE' },
    );
  }
  if (strategy === 'shadcn-components' && !shadcnConfig) {
    throw new DesignomeError(
      'shadcn/ui strategy was requested but components.json was not detected',
      { code: 'STYLE_STRATEGY_UNAVAILABLE' },
    );
  }
  return {
    system: detectedSystem,
    strategy,
    version: tailwindVersion,
    evidence: [...shadcnEvidence, ...tailwindEvidence],
    ...(shadcnConfig
      ? {
          shadcn: {
            style: shadcnConfig.style ?? null,
            base: shadcnConfig.base ?? null,
            iconLibrary: shadcnConfig.iconLibrary ?? null,
            rsc: shadcnConfig.rsc ?? null,
            cssVariables: shadcnConfig.tailwind?.cssVariables ?? null,
            aliases: shadcnConfig.aliases ?? {},
          },
        }
      : {}),
  };
}

async function assertProjectRoot(projectRoot) {
  const requested = path.resolve(projectRoot);
  const resolved = await fs.realpath(requested).catch(() => requested);
  const filesystemRoot = path.parse(resolved).root;
  if (resolved === filesystemRoot || resolved === path.resolve(os.homedir())) {
    throw new DesignomeError(
      'Refusing to use a broad filesystem or home directory as a target project',
      {
        code: 'UNSAFE_TARGET_PROJECT',
      },
    );
  }
  const stat = await fs.stat(resolved).catch(() => null);
  if (!stat?.isDirectory()) {
    throw new DesignomeError(`Target project is not a directory: ${resolved}`, {
      code: 'TARGET_PROJECT_MISSING',
    });
  }
  const markers = [
    '.git',
    'package.json',
    'pyproject.toml',
    'Cargo.toml',
    'composer.json',
  ];
  const hasMarker = (
    await Promise.all(
      markers.map((marker) => pathExists(path.join(resolved, marker))),
    )
  ).some(Boolean);
  if (!hasMarker) {
    throw new DesignomeError('Target path does not look like a project root', {
      code: 'INVALID_TARGET_PROJECT',
      details: [`Expected one of: ${markers.join(', ')}`],
    });
  }
  return resolved;
}

async function assertManagedDirectorySafe(projectRoot) {
  const managedDirectory = path.join(projectRoot, '.designome');
  if (!(await pathExists(managedDirectory))) return;
  const stat = await fs.stat(managedDirectory);
  if (!stat.isDirectory()) {
    throw new DesignomeError('.designome exists but is not a directory', {
      code: 'UNSAFE_MANAGED_DIRECTORY',
    });
  }
  const realManagedDirectory = await fs.realpath(managedDirectory);
  relativeInside(projectRoot, realManagedDirectory, '.designome directory');
}

async function resolveCssEntry(projectRoot, requestedEntry) {
  if (requestedEntry) {
    const candidate = resolveProjectPath(
      projectRoot,
      requestedEntry,
      '--css-entry',
    );
    if (!(await pathExists(candidate))) {
      throw new DesignomeError(`CSS entry does not exist: ${requestedEntry}`, {
        code: 'CSS_ENTRY_MISSING',
      });
    }
    const resolved = await fs.realpath(candidate);
    relativeInside(projectRoot, resolved, '--css-entry');
    const stat = await fs.stat(resolved);
    if (!stat.isFile()) {
      throw new DesignomeError(`CSS entry is not a file: ${requestedEntry}`, {
        code: 'INVALID_CSS_ENTRY',
      });
    }
    return resolved;
  }

  const matches = [];
  for (const candidate of cssCandidates) {
    const candidatePath = path.join(projectRoot, candidate);
    if (await pathExists(candidatePath)) {
      const resolvedCandidate = await fs.realpath(candidatePath);
      relativeInside(projectRoot, resolvedCandidate, 'discovered CSS entry');
      matches.push(resolvedCandidate);
    }
  }
  if (matches.length !== 1) {
    throw new DesignomeError(
      matches.length === 0
        ? 'No supported CSS entry was discovered; pass --css-entry'
        : 'Multiple CSS entries were discovered; pass --css-entry',
      {
        code: 'CSS_ENTRY_AMBIGUOUS',
        details: matches.map((match) =>
          toPosixPath(path.relative(projectRoot, match)),
        ),
      },
    );
  }
  return matches[0];
}

async function discoverInstructionFiles(projectRoot, cssEntryPath) {
  const results = [];
  const relativeDirectory = path.relative(
    projectRoot,
    path.dirname(cssEntryPath),
  );
  const segments =
    relativeDirectory === '' ? [] : relativeDirectory.split(path.sep);
  let current = projectRoot;
  for (const segment of ['', ...segments]) {
    if (segment) current = path.join(current, segment);
    for (const name of ['AGENTS.md', 'CLAUDE.md']) {
      const candidate = path.join(current, name);
      if ((await pathExists(candidate)) && !results.includes(candidate))
        results.push(candidate);
    }
  }
  return results.map((result) =>
    toPosixPath(path.relative(projectRoot, result)),
  );
}

function manifestArtifact(manifest, relativePath, kind) {
  return manifest?.managedArtifacts?.find(
    (artifact) => artifact.path === relativePath && artifact.kind === kind,
  );
}

async function inspectOwnedFile(
  projectRoot,
  relativePath,
  desiredContent,
  previousManifest,
) {
  const absolutePath = path.join(projectRoot, relativePath);
  const current = await readTextIfExists(absolutePath);
  const previous = manifestArtifact(previousManifest, relativePath, 'file');
  if (!previous && current !== null) {
    return {
      path: relativePath,
      kind: 'file',
      action: 'conflict',
      reason: 'Existing file is not owned by the manifest.',
    };
  }
  if (previous && current === null) {
    return {
      path: relativePath,
      kind: 'file',
      action: 'conflict',
      reason: 'Previously managed file is missing.',
    };
  }
  if (previous && sha256(current) !== previous.sha256) {
    return {
      path: relativePath,
      kind: 'file',
      action: 'conflict',
      reason: 'Managed file was modified outside Designome.',
    };
  }
  return {
    path: relativePath,
    kind: 'file',
    action:
      current === null
        ? 'create'
        : current === desiredContent
          ? 'unchanged'
          : 'update',
    content: desiredContent,
    sha256: sha256(desiredContent),
  };
}

async function inspectBlockFile({
  projectRoot,
  relativePath,
  desiredBlock,
  startMarker,
  endMarker,
  placement,
  previousManifest,
}) {
  const absolutePath = path.join(projectRoot, relativePath);
  const current = (await readTextIfExists(absolutePath)) ?? '';
  const inspection = inspectManagedBlock(current, startMarker, endMarker);
  const previous = manifestArtifact(previousManifest, relativePath, 'block');

  if (!previous && (inspection.startCount !== 0 || inspection.endCount !== 0)) {
    return {
      path: relativePath,
      kind: 'block',
      action: 'conflict',
      reason: 'Existing managed markers are not owned by the manifest.',
    };
  }
  if (previous) {
    if (
      inspection.startCount !== 1 ||
      inspection.endCount !== 1 ||
      inspection.block === null
    ) {
      return {
        path: relativePath,
        kind: 'block',
        action: 'conflict',
        reason: 'Managed markers are missing or duplicated.',
      };
    }
    if (sha256(inspection.block) !== previous.sha256) {
      return {
        path: relativePath,
        kind: 'block',
        action: 'conflict',
        reason: 'Managed block was modified outside Designome.',
      };
    }
  }

  let desiredContent;
  try {
    desiredContent = upsertManagedBlock(
      current,
      desiredBlock,
      startMarker,
      endMarker,
      { placement },
    );
  } catch (error) {
    return {
      path: relativePath,
      kind: 'block',
      action: 'conflict',
      reason: error.message,
    };
  }
  return {
    path: relativePath,
    kind: 'block',
    action:
      current === ''
        ? 'create'
        : current === desiredContent
          ? 'unchanged'
          : 'update',
    content: desiredContent,
    blockSha256: sha256(desiredBlock),
    startMarker,
    endMarker,
  };
}

function publicAction(action) {
  const {
    content,
    blockSha256,
    startMarker,
    endMarker,
    sha256: contentSha,
    ...safe
  } = action;
  return safe;
}

export async function planInstallation({
  dnaPath,
  projectPath,
  cssEntry,
  scope = ':root',
  documentationDirectory = defaultDocumentationDirectory,
  rulePrecedence = 'complement',
  existingRulePaths = [],
  stylingStrategy = 'auto',
  instructionsReviewed = false,
}) {
  if (![':root', '[data-designome]'].includes(scope)) {
    throw new DesignomeError(
      'CSS scope must be either :root or [data-designome]',
      { code: 'INVALID_CSS_SCOPE' },
    );
  }
  if (
    !['complement', 'existing-first', 'designome-first'].includes(
      rulePrecedence,
    )
  ) {
    throw new DesignomeError(
      'Rule precedence must be complement, existing-first, or designome-first',
      {
        code: 'INVALID_RULE_PRECEDENCE',
      },
    );
  }
  if (
    ![
      'auto',
      'css-variables',
      'tailwind-utilities',
      'shadcn-components',
    ].includes(stylingStrategy)
  ) {
    throw new DesignomeError(
      'Styling strategy must be auto, css-variables, tailwind-utilities, or shadcn-components',
      {
        code: 'INVALID_STYLE_STRATEGY',
      },
    );
  }

  const projectRoot = await assertProjectRoot(projectPath);
  await assertManagedDirectorySafe(projectRoot);
  const resolvedDnaPath = path.resolve(dnaPath);
  const dna = await readJson(resolvedDnaPath).catch((error) => {
    throw new DesignomeError(`Cannot read Design DNA: ${resolvedDnaPath}`, {
      code: 'DESIGN_DNA_UNREADABLE',
      details: [error.message],
    });
  });
  await assertValidDesignDna(dna, { requireAccepted: true });

  const resolvedCssEntry = await resolveCssEntry(projectRoot, cssEntry);
  const cssEntryRelative = toPosixPath(
    relativeInside(projectRoot, resolvedCssEntry, 'CSS entry'),
  );
  const cssDirectory = path.dirname(resolvedCssEntry);
  const resolvedDocumentationDirectory = resolveProjectPath(
    projectRoot,
    documentationDirectory,
    '--docs-dir',
  );
  const documentationRelative = toPosixPath(
    relativeInside(projectRoot, resolvedDocumentationDirectory, '--docs-dir'),
  );
  if (
    !documentationRelative ||
    documentationRelative === '.' ||
    documentationRelative.startsWith('.designome')
  ) {
    throw new DesignomeError(
      'Documentation directory must be a visible project-relative directory outside .designome',
      {
        code: 'INVALID_DOCUMENTATION_DIRECTORY',
      },
    );
  }
  const normalizedExistingRulePaths = [];
  for (const rulePath of existingRulePaths) {
    const absoluteRulePath = resolveProjectPath(
      projectRoot,
      rulePath,
      '--existing-rules',
    );
    if (!(await pathExists(absoluteRulePath))) {
      throw new DesignomeError(
        `Declared existing rule path does not exist: ${rulePath}`,
        {
          code: 'EXISTING_RULE_PATH_MISSING',
        },
      );
    }
    normalizedExistingRulePaths.push(
      toPosixPath(
        relativeInside(
          projectRoot,
          await fs.realpath(absoluteRulePath),
          '--existing-rules',
        ),
      ),
    );
  }
  const styling = await detectStylingContext(
    projectRoot,
    resolvedCssEntry,
    stylingStrategy,
  );
  const integrationPolicy = {
    rulePrecedence,
    existingRulePaths: [...new Set(normalizedExistingRulePaths)].sort(),
  };
  const generatedCssPath = path.join(cssDirectory, 'designome.generated.css');
  const overridesCssPath = path.join(cssDirectory, 'designome.overrides.css');
  if (
    resolvedCssEntry === generatedCssPath ||
    resolvedCssEntry === overridesCssPath
  ) {
    throw new DesignomeError(
      'The CSS entry cannot be a Designome-managed CSS file',
      {
        code: 'INVALID_CSS_ENTRY',
      },
    );
  }

  const generatedCssRelative = toPosixPath(
    relativeInside(projectRoot, generatedCssPath),
  );
  const overridesCssRelative = toPosixPath(
    relativeInside(projectRoot, overridesCssPath),
  );
  const agentsRelative = 'AGENTS.md';
  const manifestPath = path.join(projectRoot, manifestRelativePath);
  const previousManifest = (await pathExists(manifestPath))
    ? await readJson(manifestPath)
    : null;
  if (
    previousManifest &&
    !supportedManifestVersions.has(previousManifest.schemaVersion)
  ) {
    throw new DesignomeError('Installed manifest version is unsupported', {
      code: 'UNSUPPORTED_MANIFEST',
    });
  }

  const generatedCss = renderGeneratedCss(dna, scope, styling);
  const dnaText = jsonText(dna);
  const importBlock = renderCssImportBlock(
    path.basename(generatedCssPath),
    path.basename(overridesCssPath),
  );
  const guidanceBlock = renderGuidanceBlock({
    documentationDirectory: documentationRelative,
    integrationPolicy,
    styling,
  });
  const documentation = renderDocumentation({
    dna,
    styling,
    integrationPolicy,
    documentationDirectory: documentationRelative,
  });
  const auditSkill = new Map([
    [
      'SKILL.md',
      await fs.readFile(
        path.join(pluginRoot, 'skills', 'designome-audit', 'SKILL.md'),
        'utf8',
      ),
    ],
    [
      'agents/openai.yaml',
      await fs.readFile(
        path.join(
          pluginRoot,
          'skills',
          'designome-audit',
          'agents',
          'openai.yaml',
        ),
        'utf8',
      ),
    ],
  ]);
  const instructionFiles = await discoverInstructionFiles(
    projectRoot,
    resolvedCssEntry,
  );

  const actions = [];
  actions.push(
    await inspectOwnedFile(
      projectRoot,
      installedDnaRelativePath,
      dnaText,
      previousManifest,
    ),
  );
  for (const [filename, content] of documentation) {
    actions.push(
      await inspectOwnedFile(
        projectRoot,
        toPosixPath(path.join(documentationRelative, filename)),
        content,
        previousManifest,
      ),
    );
  }
  for (const [filename, content] of auditSkill) {
    actions.push(
      await inspectOwnedFile(
        projectRoot,
        toPosixPath(path.join(auditSkillRelativeDirectory, filename)),
        content,
        previousManifest,
      ),
    );
  }
  actions.push(
    await inspectOwnedFile(
      projectRoot,
      generatedCssRelative,
      generatedCss,
      previousManifest,
    ),
  );
  actions.push(
    await inspectBlockFile({
      projectRoot,
      relativePath: cssEntryRelative,
      desiredBlock: importBlock,
      startMarker: cssStartMarker,
      endMarker: cssEndMarker,
      placement: 'css-top',
      previousManifest,
    }),
  );
  actions.push(
    await inspectBlockFile({
      projectRoot,
      relativePath: agentsRelative,
      desiredBlock: guidanceBlock,
      startMarker: guidanceStartMarker,
      endMarker: guidanceEndMarker,
      placement: 'append',
      previousManifest,
    }),
  );

  const overridesCurrent = await readTextIfExists(overridesCssPath);
  actions.push({
    path: overridesCssRelative,
    kind: 'user-owned',
    action: overridesCurrent === null ? 'create' : 'preserve',
    content: overridesCurrent === null ? renderOverridesCss() : null,
  });
  const auditConfigPath = path.join(projectRoot, auditConfigRelativePath);
  const auditConfigCurrent = await readTextIfExists(auditConfigPath);
  actions.push({
    path: auditConfigRelativePath,
    kind: 'user-owned',
    action: auditConfigCurrent === null ? 'create' : 'preserve',
    content: auditConfigCurrent === null ? renderAuditConfig() : null,
  });

  const conflicts = actions.filter((action) => action.action === 'conflict');
  const packageJson = await readJson(path.join(pluginRoot, 'package.json'));
  const dnaHash = sha256(dnaText);
  const configurationFingerprint = sha256(
    jsonText({
      dnaHash,
      cssEntryRelative,
      generatedCssRelative,
      overridesCssRelative,
      scope,
      documentationRelative,
      integrationPolicy,
      styling,
    }),
  );
  const installedAt =
    previousManifest?.configurationFingerprint === configurationFingerprint
      ? previousManifest.installedAt
      : new Date().toISOString();

  const managedArtifacts = actions
    .filter((action) => action.kind === 'file' || action.kind === 'block')
    .filter((action) => action.action !== 'conflict')
    .map((action) =>
      action.kind === 'file'
        ? { path: action.path, kind: 'file', sha256: action.sha256 }
        : {
            path: action.path,
            kind: 'block',
            sha256: action.blockSha256,
            startMarker: action.startMarker,
            endMarker: action.endMarker,
          },
    );
  const manifest = {
    schemaVersion: '0.2.0',
    pluginVersion: packageJson.version,
    installedAt,
    configurationFingerprint,
    dna: {
      documentId: dna.documentId,
      revision: dna.revision.number,
      sha256: dnaHash,
    },
    adapter: {
      cssEntry: cssEntryRelative,
      generatedCss: generatedCssRelative,
      overridesCss: overridesCssRelative,
      scope,
      documentationDirectory: documentationRelative,
      styling,
      integrationPolicy,
      instructionFiles,
      instructionsReviewed:
        instructionsReviewed ||
        previousManifest?.adapter?.instructionsReviewed === true,
    },
    managedArtifacts,
    userOwnedArtifacts: [
      { path: overridesCssRelative, kind: 'file', rewritePolicy: 'preserve' },
      {
        path: auditConfigRelativePath,
        kind: 'file',
        rewritePolicy: 'preserve',
      },
    ],
  };
  const manifestText = jsonText(manifest);
  const currentManifestText = await readTextIfExists(manifestPath);
  const manifestAction = {
    path: manifestRelativePath,
    kind: 'manifest',
    action:
      conflicts.length > 0
        ? 'blocked'
        : currentManifestText === null
          ? 'create'
          : currentManifestText === manifestText
            ? 'unchanged'
            : 'update',
    content: manifestText,
  };
  actions.push(manifestAction);

  return {
    status: conflicts.length > 0 ? 'conflict' : 'ready',
    projectRoot,
    dnaPath: resolvedDnaPath,
    dna,
    manifest,
    actions,
    publicPlan: {
      status: conflicts.length > 0 ? 'conflict' : 'ready',
      dna: manifest.dna,
      adapter: manifest.adapter,
      actions: actions.map(publicAction),
      conflictCount: conflicts.length,
    },
  };
}

export async function installDesignDna(options) {
  const plan = await planInstallation(options);
  if (plan.status === 'conflict' || options.dryRun) return plan.publicPlan;
  if (!options.instructionsReviewed) {
    throw new DesignomeError(
      'Writing requires --instructions-reviewed after the dry-run and instruction review',
      {
        code: 'INSTRUCTIONS_NOT_REVIEWED',
      },
    );
  }

  const writeActions = plan.actions.filter((action) =>
    ['create', 'update'].includes(action.action),
  );
  const backups = [];
  try {
    for (const action of writeActions) {
      const absolutePath = path.join(plan.projectRoot, action.path);
      backups.push({
        path: absolutePath,
        content: await readTextIfExists(absolutePath),
      });
      await atomicWrite(absolutePath, action.content);
    }
  } catch (error) {
    await rollbackWrites(backups);
    throw new DesignomeError(
      'Installation failed and completed writes were rolled back',
      {
        code: 'INSTALLATION_ROLLED_BACK',
        details: [error.message],
      },
    );
  }

  const verification = await verifyInstallation({
    projectPath: plan.projectRoot,
  });
  if (!verification.valid) {
    await rollbackWrites(backups);
    throw new DesignomeError(
      'Post-install verification failed and installation was rolled back',
      {
        code: 'POST_INSTALL_VERIFICATION_FAILED',
        details: verification.errors,
      },
    );
  }

  return {
    ...plan.publicPlan,
    status: 'installed',
    verification: 'passed',
  };
}

export async function verifyInstallation({ projectPath }) {
  const projectRoot = await assertProjectRoot(projectPath);
  await assertManagedDirectorySafe(projectRoot);
  const errors = [];
  const manifestPath = path.join(projectRoot, manifestRelativePath);
  if (!(await pathExists(manifestPath))) {
    return {
      valid: false,
      projectRoot,
      errors: ['.designome/manifest.json is missing'],
    };
  }

  let manifest;
  try {
    manifest = await readJson(manifestPath);
  } catch (error) {
    return {
      valid: false,
      projectRoot,
      errors: [`Cannot parse manifest: ${error.message}`],
    };
  }
  if (!supportedManifestVersions.has(manifest.schemaVersion))
    errors.push('Unsupported manifest schemaVersion');

  for (const artifact of manifest.managedArtifacts ?? []) {
    let absolutePath;
    try {
      absolutePath = resolveProjectPath(
        projectRoot,
        artifact.path,
        'managed artifact path',
      );
    } catch (error) {
      errors.push(`Unsafe managed artifact path: ${String(artifact.path)}`);
      continue;
    }
    const content = await readTextIfExists(absolutePath);
    if (content === null) {
      errors.push(`Managed artifact is missing: ${artifact.path}`);
      continue;
    }
    if (artifact.kind === 'file') {
      if (sha256(content) !== artifact.sha256)
        errors.push(`Managed file checksum mismatch: ${artifact.path}`);
      continue;
    }
    if (artifact.kind === 'block') {
      const block = inspectManagedBlock(
        content,
        artifact.startMarker,
        artifact.endMarker,
      );
      if (
        block.startCount !== 1 ||
        block.endCount !== 1 ||
        block.block === null
      ) {
        errors.push(
          `Managed block markers are missing or duplicated: ${artifact.path}`,
        );
      } else if (sha256(block.block) !== artifact.sha256) {
        errors.push(`Managed block checksum mismatch: ${artifact.path}`);
      }
    }
  }

  for (const artifact of manifest.userOwnedArtifacts ?? []) {
    let absolutePath;
    try {
      absolutePath = resolveProjectPath(
        projectRoot,
        artifact.path,
        'user-owned artifact path',
      );
    } catch (error) {
      errors.push(`Unsafe user-owned artifact path: ${String(artifact.path)}`);
      continue;
    }
    if (!(await pathExists(absolutePath))) {
      errors.push(`User-owned override artifact is missing: ${artifact.path}`);
    }
  }

  const installedDnaPath = path.join(projectRoot, installedDnaRelativePath);
  if (await pathExists(installedDnaPath)) {
    try {
      const dna = await readJson(installedDnaPath);
      errors.push(
        ...(await validateDesignDna(dna, { requireAccepted: true })).map(
          (error) => `Design DNA: ${error}`,
        ),
      );
      if (sha256(jsonText(dna)) !== manifest.dna?.sha256)
        errors.push('Installed Design DNA does not match manifest DNA hash');
    } catch (error) {
      errors.push(`Cannot validate installed Design DNA: ${error.message}`);
    }
  }

  return {
    valid: errors.length === 0,
    projectRoot,
    documentId: manifest.dna?.documentId ?? null,
    revision: manifest.dna?.revision ?? null,
    managedArtifactCount: manifest.managedArtifacts?.length ?? 0,
    errors,
  };
}
