import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { assertValidDesignDna, validateDesignDna } from './design-dna.mjs';
import { DesignomeError } from './errors.mjs';
import {
  atomicWrite,
  jsonText,
  pathExists,
  pluginRoot,
  readJson,
  readTextIfExists,
  relativeInside,
  resolveProjectPath,
  rollbackWrites,
  sha256,
  toPosixPath,
} from './files.mjs';
import { inspectManagedBlock, upsertManagedBlock } from './markers.mjs';

const manifestRelativePath = '.designome/manifest.json';
const installedDnaRelativePath = '.designome/design-dna.json';
const cssStartMarker = '/* designome:generated-import:start */';
const cssEndMarker = '/* designome:generated-import:end */';
const guidanceStartMarker = '<!-- designome:guidance:start -->';
const guidanceEndMarker = '<!-- designome:guidance:end -->';

const cssCandidates = [
  'src/app/globals.css',
  'app/globals.css',
  'src/styles/globals.css',
  'styles/globals.css',
  'src/index.css',
  'src/main.css',
];

function safeCssComment(value) {
  return String(value)
    .replace(/\*\//gu, '* /')
    .replace(/[\r\n]+/gu, ' ');
}

function cssName(tokenId) {
  return tokenId
    .replace(/^token\./u, '')
    .replace(/[^a-zA-Z0-9-]+/gu, '-')
    .replace(/-+/gu, '-')
    .replace(/^-|-$/gu, '')
    .toLowerCase();
}

function cssValue(value, tokenId) {
  const rendered = String(value);
  if (
    /[;{}\r\n]/u.test(rendered) ||
    rendered.includes('/*') ||
    rendered.includes('*/')
  ) {
    throw new DesignomeError(`Unsafe literal CSS value in ${tokenId}`, {
      code: 'UNSAFE_CSS_TOKEN',
    });
  }
  return rendered;
}

function renderGeneratedCss(dna, scope) {
  const exactTokens = [];
  const nonLiteralTokens = [];
  const generatedNames = new Set();
  for (const token of dna.tokens) {
    const generatedName = cssName(token.id);
    if (generatedNames.has(generatedName)) {
      throw new DesignomeError(`CSS token name collision for ${token.id}`, {
        code: 'CSS_TOKEN_COLLISION',
      });
    }
    generatedNames.add(generatedName);
    if (token.value?.kind === 'exact') {
      exactTokens.push(
        `    --designome-${generatedName}: ${cssValue(token.value.value, token.id)};`,
      );
    } else {
      const explanation =
        token.value?.expression ??
        token.value?.reason ??
        (token.value?.kind === 'range'
          ? `${token.value.minimum} to ${token.value.maximum} ${token.value.unit}`
          : 'No literal CSS value is available.');
      nonLiteralTokens.push(
        `  /* ${safeCssComment(token.id)}: ${safeCssComment(explanation)} */`,
      );
    }
  }

  const lines = [
    `/* Generated by Designome from ${safeCssComment(dna.documentId)} revision ${dna.revision.number}. */`,
    '/* Do not edit this file. Put project-owned changes in designome.overrides.css. */',
    '',
    '@layer designome.tokens {',
    `  ${scope} {`,
    ...(exactTokens.length > 0
      ? exactTokens
      : ['    /* No exact token values were accepted. */']),
    '  }',
    ...(nonLiteralTokens.length > 0 ? ['', ...nonLiteralTokens] : []),
    '}',
    '',
  ];
  return lines.join('\n');
}

function renderOverridesCss() {
  return [
    '/* Project-owned Designome overrides. This file is never overwritten. */',
    '@layer designome.overrides {',
    '  /* Add intentional local overrides here. */',
    '}',
    '',
  ].join('\n');
}

function renderCssImportBlock(generatedName, overridesName) {
  return [
    cssStartMarker,
    `@import "./${generatedName}";`,
    `@import "./${overridesName}";`,
    cssEndMarker,
    '',
  ].join('\n');
}

function renderGuidanceBlock() {
  return [
    guidanceStartMarker,
    '## Designome-generated UI',
    '',
    'Read `.designome/design-dna.json` and use `$designome-extract`, `$designome-install`, or `$designome-audit` as appropriate.',
    'Preserve claim status, use accepted generated tokens, cover applicable business states and stress cases, and audit generated UI before delivery.',
    guidanceEndMarker,
    '',
  ].join('\n');
}

async function assertProjectRoot(projectRoot) {
  const requested = path.resolve(projectRoot);
  const resolved = await fs.realpath(requested).catch(() => requested);
  const filesystemRoot = path.parse(resolved).root;
  if (resolved === filesystemRoot || resolved === path.resolve(os.homedir())) {
    throw new DesignomeError(
      'Refusing to use a broad filesystem or home directory as a target project',
      {
        code: 'UNSAFE_TARGET_PROJECT',
      },
    );
  }
  const stat = await fs.stat(resolved).catch(() => null);
  if (!stat?.isDirectory()) {
    throw new DesignomeError(`Target project is not a directory: ${resolved}`, {
      code: 'TARGET_PROJECT_MISSING',
    });
  }
  const markers = [
    '.git',
    'package.json',
    'pyproject.toml',
    'Cargo.toml',
    'composer.json',
  ];
  const hasMarker = (
    await Promise.all(
      markers.map((marker) => pathExists(path.join(resolved, marker))),
    )
  ).some(Boolean);
  if (!hasMarker) {
    throw new DesignomeError('Target path does not look like a project root', {
      code: 'INVALID_TARGET_PROJECT',
      details: [`Expected one of: ${markers.join(', ')}`],
    });
  }
  return resolved;
}

async function assertManagedDirectorySafe(projectRoot) {
  const managedDirectory = path.join(projectRoot, '.designome');
  if (!(await pathExists(managedDirectory))) return;
  const stat = await fs.stat(managedDirectory);
  if (!stat.isDirectory()) {
    throw new DesignomeError('.designome exists but is not a directory', {
      code: 'UNSAFE_MANAGED_DIRECTORY',
    });
  }
  const realManagedDirectory = await fs.realpath(managedDirectory);
  relativeInside(projectRoot, realManagedDirectory, '.designome directory');
}

async function resolveCssEntry(projectRoot, requestedEntry) {
  if (requestedEntry) {
    const candidate = resolveProjectPath(
      projectRoot,
      requestedEntry,
      '--css-entry',
    );
    if (!(await pathExists(candidate))) {
      throw new DesignomeError(`CSS entry does not exist: ${requestedEntry}`, {
        code: 'CSS_ENTRY_MISSING',
      });
    }
    const resolved = await fs.realpath(candidate);
    relativeInside(projectRoot, resolved, '--css-entry');
    const stat = await fs.stat(resolved);
    if (!stat.isFile()) {
      throw new DesignomeError(`CSS entry is not a file: ${requestedEntry}`, {
        code: 'INVALID_CSS_ENTRY',
      });
    }
    return resolved;
  }

  const matches = [];
  for (const candidate of cssCandidates) {
    const candidatePath = path.join(projectRoot, candidate);
    if (await pathExists(candidatePath)) {
      const resolvedCandidate = await fs.realpath(candidatePath);
      relativeInside(projectRoot, resolvedCandidate, 'discovered CSS entry');
      matches.push(resolvedCandidate);
    }
  }
  if (matches.length !== 1) {
    throw new DesignomeError(
      matches.length === 0
        ? 'No supported CSS entry was discovered; pass --css-entry'
        : 'Multiple CSS entries were discovered; pass --css-entry',
      {
        code: 'CSS_ENTRY_AMBIGUOUS',
        details: matches.map((match) =>
          toPosixPath(path.relative(projectRoot, match)),
        ),
      },
    );
  }
  return matches[0];
}

async function discoverInstructionFiles(projectRoot, cssEntryPath) {
  const results = [];
  const relativeDirectory = path.relative(
    projectRoot,
    path.dirname(cssEntryPath),
  );
  const segments =
    relativeDirectory === '' ? [] : relativeDirectory.split(path.sep);
  let current = projectRoot;
  for (const segment of ['', ...segments]) {
    if (segment) current = path.join(current, segment);
    for (const name of ['AGENTS.md', 'CLAUDE.md']) {
      const candidate = path.join(current, name);
      if ((await pathExists(candidate)) && !results.includes(candidate))
        results.push(candidate);
    }
  }
  return results.map((result) =>
    toPosixPath(path.relative(projectRoot, result)),
  );
}

function manifestArtifact(manifest, relativePath, kind) {
  return manifest?.managedArtifacts?.find(
    (artifact) => artifact.path === relativePath && artifact.kind === kind,
  );
}

async function inspectOwnedFile(
  projectRoot,
  relativePath,
  desiredContent,
  previousManifest,
) {
  const absolutePath = path.join(projectRoot, relativePath);
  const current = await readTextIfExists(absolutePath);
  const previous = manifestArtifact(previousManifest, relativePath, 'file');
  if (!previous && current !== null) {
    return {
      path: relativePath,
      kind: 'file',
      action: 'conflict',
      reason: 'Existing file is not owned by the manifest.',
    };
  }
  if (previous && current === null) {
    return {
      path: relativePath,
      kind: 'file',
      action: 'conflict',
      reason: 'Previously managed file is missing.',
    };
  }
  if (previous && sha256(current) !== previous.sha256) {
    return {
      path: relativePath,
      kind: 'file',
      action: 'conflict',
      reason: 'Managed file was modified outside Designome.',
    };
  }
  return {
    path: relativePath,
    kind: 'file',
    action:
      current === null
        ? 'create'
        : current === desiredContent
          ? 'unchanged'
          : 'update',
    content: desiredContent,
    sha256: sha256(desiredContent),
  };
}

async function inspectBlockFile({
  projectRoot,
  relativePath,
  desiredBlock,
  startMarker,
  endMarker,
  placement,
  previousManifest,
}) {
  const absolutePath = path.join(projectRoot, relativePath);
  const current = (await readTextIfExists(absolutePath)) ?? '';
  const inspection = inspectManagedBlock(current, startMarker, endMarker);
  const previous = manifestArtifact(previousManifest, relativePath, 'block');

  if (!previous && (inspection.startCount !== 0 || inspection.endCount !== 0)) {
    return {
      path: relativePath,
      kind: 'block',
      action: 'conflict',
      reason: 'Existing managed markers are not owned by the manifest.',
    };
  }
  if (previous) {
    if (
      inspection.startCount !== 1 ||
      inspection.endCount !== 1 ||
      inspection.block === null
    ) {
      return {
        path: relativePath,
        kind: 'block',
        action: 'conflict',
        reason: 'Managed markers are missing or duplicated.',
      };
    }
    if (sha256(inspection.block) !== previous.sha256) {
      return {
        path: relativePath,
        kind: 'block',
        action: 'conflict',
        reason: 'Managed block was modified outside Designome.',
      };
    }
  }

  let desiredContent;
  try {
    desiredContent = upsertManagedBlock(
      current,
      desiredBlock,
      startMarker,
      endMarker,
      { placement },
    );
  } catch (error) {
    return {
      path: relativePath,
      kind: 'block',
      action: 'conflict',
      reason: error.message,
    };
  }
  return {
    path: relativePath,
    kind: 'block',
    action:
      current === ''
        ? 'create'
        : current === desiredContent
          ? 'unchanged'
          : 'update',
    content: desiredContent,
    blockSha256: sha256(desiredBlock),
    startMarker,
    endMarker,
  };
}

function publicAction(action) {
  const {
    content,
    blockSha256,
    startMarker,
    endMarker,
    sha256: contentSha,
    ...safe
  } = action;
  return safe;
}

export async function planInstallation({
  dnaPath,
  projectPath,
  cssEntry,
  scope = ':root',
  instructionsReviewed = false,
}) {
  if (![':root', '[data-designome]'].includes(scope)) {
    throw new DesignomeError(
      'CSS scope must be either :root or [data-designome]',
      { code: 'INVALID_CSS_SCOPE' },
    );
  }

  const projectRoot = await assertProjectRoot(projectPath);
  await assertManagedDirectorySafe(projectRoot);
  const resolvedDnaPath = path.resolve(dnaPath);
  const dna = await readJson(resolvedDnaPath).catch((error) => {
    throw new DesignomeError(`Cannot read Design DNA: ${resolvedDnaPath}`, {
      code: 'DESIGN_DNA_UNREADABLE',
      details: [error.message],
    });
  });
  await assertValidDesignDna(dna, { requireAccepted: true });

  const resolvedCssEntry = await resolveCssEntry(projectRoot, cssEntry);
  const cssEntryRelative = toPosixPath(
    relativeInside(projectRoot, resolvedCssEntry, 'CSS entry'),
  );
  const cssDirectory = path.dirname(resolvedCssEntry);
  const generatedCssPath = path.join(cssDirectory, 'designome.generated.css');
  const overridesCssPath = path.join(cssDirectory, 'designome.overrides.css');
  if (
    resolvedCssEntry === generatedCssPath ||
    resolvedCssEntry === overridesCssPath
  ) {
    throw new DesignomeError(
      'The CSS entry cannot be a Designome-managed CSS file',
      {
        code: 'INVALID_CSS_ENTRY',
      },
    );
  }

  const generatedCssRelative = toPosixPath(
    relativeInside(projectRoot, generatedCssPath),
  );
  const overridesCssRelative = toPosixPath(
    relativeInside(projectRoot, overridesCssPath),
  );
  const agentsRelative = 'AGENTS.md';
  const manifestPath = path.join(projectRoot, manifestRelativePath);
  const previousManifest = (await pathExists(manifestPath))
    ? await readJson(manifestPath)
    : null;
  if (previousManifest && previousManifest.schemaVersion !== '0.1.0') {
    throw new DesignomeError('Installed manifest version is unsupported', {
      code: 'UNSUPPORTED_MANIFEST',
    });
  }

  const generatedCss = renderGeneratedCss(dna, scope);
  const dnaText = jsonText(dna);
  const importBlock = renderCssImportBlock(
    path.basename(generatedCssPath),
    path.basename(overridesCssPath),
  );
  const guidanceBlock = renderGuidanceBlock();
  const instructionFiles = await discoverInstructionFiles(
    projectRoot,
    resolvedCssEntry,
  );

  const actions = [];
  actions.push(
    await inspectOwnedFile(
      projectRoot,
      installedDnaRelativePath,
      dnaText,
      previousManifest,
    ),
  );
  actions.push(
    await inspectOwnedFile(
      projectRoot,
      generatedCssRelative,
      generatedCss,
      previousManifest,
    ),
  );
  actions.push(
    await inspectBlockFile({
      projectRoot,
      relativePath: cssEntryRelative,
      desiredBlock: importBlock,
      startMarker: cssStartMarker,
      endMarker: cssEndMarker,
      placement: 'css-top',
      previousManifest,
    }),
  );
  actions.push(
    await inspectBlockFile({
      projectRoot,
      relativePath: agentsRelative,
      desiredBlock: guidanceBlock,
      startMarker: guidanceStartMarker,
      endMarker: guidanceEndMarker,
      placement: 'append',
      previousManifest,
    }),
  );

  const overridesCurrent = await readTextIfExists(overridesCssPath);
  actions.push({
    path: overridesCssRelative,
    kind: 'user-owned',
    action: overridesCurrent === null ? 'create' : 'preserve',
    content: overridesCurrent === null ? renderOverridesCss() : null,
  });

  const conflicts = actions.filter((action) => action.action === 'conflict');
  const packageJson = await readJson(path.join(pluginRoot, 'package.json'));
  const dnaHash = sha256(dnaText);
  const configurationFingerprint = sha256(
    jsonText({
      dnaHash,
      cssEntryRelative,
      generatedCssRelative,
      overridesCssRelative,
      scope,
    }),
  );
  const installedAt =
    previousManifest?.configurationFingerprint === configurationFingerprint
      ? previousManifest.installedAt
      : new Date().toISOString();

  const managedArtifacts = actions
    .filter((action) => action.kind === 'file' || action.kind === 'block')
    .filter((action) => action.action !== 'conflict')
    .map((action) =>
      action.kind === 'file'
        ? { path: action.path, kind: 'file', sha256: action.sha256 }
        : {
            path: action.path,
            kind: 'block',
            sha256: action.blockSha256,
            startMarker: action.startMarker,
            endMarker: action.endMarker,
          },
    );
  const manifest = {
    schemaVersion: '0.1.0',
    pluginVersion: packageJson.version,
    installedAt,
    configurationFingerprint,
    dna: {
      documentId: dna.documentId,
      revision: dna.revision.number,
      sha256: dnaHash,
    },
    adapter: {
      cssEntry: cssEntryRelative,
      generatedCss: generatedCssRelative,
      overridesCss: overridesCssRelative,
      scope,
      instructionFiles,
      instructionsReviewed:
        instructionsReviewed ||
        previousManifest?.adapter?.instructionsReviewed === true,
    },
    managedArtifacts,
    userOwnedArtifacts: [
      { path: overridesCssRelative, kind: 'file', rewritePolicy: 'preserve' },
    ],
  };
  const manifestText = jsonText(manifest);
  const currentManifestText = await readTextIfExists(manifestPath);
  const manifestAction = {
    path: manifestRelativePath,
    kind: 'manifest',
    action:
      conflicts.length > 0
        ? 'blocked'
        : currentManifestText === null
          ? 'create'
          : currentManifestText === manifestText
            ? 'unchanged'
            : 'update',
    content: manifestText,
  };
  actions.push(manifestAction);

  return {
    status: conflicts.length > 0 ? 'conflict' : 'ready',
    projectRoot,
    dnaPath: resolvedDnaPath,
    dna,
    manifest,
    actions,
    publicPlan: {
      status: conflicts.length > 0 ? 'conflict' : 'ready',
      dna: manifest.dna,
      adapter: manifest.adapter,
      actions: actions.map(publicAction),
      conflictCount: conflicts.length,
    },
  };
}

export async function installDesignDna(options) {
  const plan = await planInstallation(options);
  if (plan.status === 'conflict' || options.dryRun) return plan.publicPlan;
  if (!options.instructionsReviewed) {
    throw new DesignomeError(
      'Writing requires --instructions-reviewed after the dry-run and instruction review',
      {
        code: 'INSTRUCTIONS_NOT_REVIEWED',
      },
    );
  }

  const writeActions = plan.actions.filter((action) =>
    ['create', 'update'].includes(action.action),
  );
  const backups = [];
  try {
    for (const action of writeActions) {
      const absolutePath = path.join(plan.projectRoot, action.path);
      backups.push({
        path: absolutePath,
        content: await readTextIfExists(absolutePath),
      });
      await atomicWrite(absolutePath, action.content);
    }
  } catch (error) {
    await rollbackWrites(backups);
    throw new DesignomeError(
      'Installation failed and completed writes were rolled back',
      {
        code: 'INSTALLATION_ROLLED_BACK',
        details: [error.message],
      },
    );
  }

  const verification = await verifyInstallation({
    projectPath: plan.projectRoot,
  });
  if (!verification.valid) {
    await rollbackWrites(backups);
    throw new DesignomeError(
      'Post-install verification failed and installation was rolled back',
      {
        code: 'POST_INSTALL_VERIFICATION_FAILED',
        details: verification.errors,
      },
    );
  }

  return {
    ...plan.publicPlan,
    status: 'installed',
    verification: 'passed',
  };
}

export async function verifyInstallation({ projectPath }) {
  const projectRoot = await assertProjectRoot(projectPath);
  await assertManagedDirectorySafe(projectRoot);
  const errors = [];
  const manifestPath = path.join(projectRoot, manifestRelativePath);
  if (!(await pathExists(manifestPath))) {
    return {
      valid: false,
      projectRoot,
      errors: ['.designome/manifest.json is missing'],
    };
  }

  let manifest;
  try {
    manifest = await readJson(manifestPath);
  } catch (error) {
    return {
      valid: false,
      projectRoot,
      errors: [`Cannot parse manifest: ${error.message}`],
    };
  }
  if (manifest.schemaVersion !== '0.1.0')
    errors.push('Unsupported manifest schemaVersion');

  for (const artifact of manifest.managedArtifacts ?? []) {
    let absolutePath;
    try {
      absolutePath = resolveProjectPath(
        projectRoot,
        artifact.path,
        'managed artifact path',
      );
    } catch (error) {
      errors.push(`Unsafe managed artifact path: ${String(artifact.path)}`);
      continue;
    }
    const content = await readTextIfExists(absolutePath);
    if (content === null) {
      errors.push(`Managed artifact is missing: ${artifact.path}`);
      continue;
    }
    if (artifact.kind === 'file') {
      if (sha256(content) !== artifact.sha256)
        errors.push(`Managed file checksum mismatch: ${artifact.path}`);
      continue;
    }
    if (artifact.kind === 'block') {
      const block = inspectManagedBlock(
        content,
        artifact.startMarker,
        artifact.endMarker,
      );
      if (
        block.startCount !== 1 ||
        block.endCount !== 1 ||
        block.block === null
      ) {
        errors.push(
          `Managed block markers are missing or duplicated: ${artifact.path}`,
        );
      } else if (sha256(block.block) !== artifact.sha256) {
        errors.push(`Managed block checksum mismatch: ${artifact.path}`);
      }
    }
  }

  for (const artifact of manifest.userOwnedArtifacts ?? []) {
    let absolutePath;
    try {
      absolutePath = resolveProjectPath(
        projectRoot,
        artifact.path,
        'user-owned artifact path',
      );
    } catch (error) {
      errors.push(`Unsafe user-owned artifact path: ${String(artifact.path)}`);
      continue;
    }
    if (!(await pathExists(absolutePath))) {
      errors.push(`User-owned override artifact is missing: ${artifact.path}`);
    }
  }

  const installedDnaPath = path.join(projectRoot, installedDnaRelativePath);
  if (await pathExists(installedDnaPath)) {
    try {
      const dna = await readJson(installedDnaPath);
      errors.push(
        ...(await validateDesignDna(dna, { requireAccepted: true })).map(
          (error) => `Design DNA: ${error}`,
        ),
      );
      if (sha256(jsonText(dna)) !== manifest.dna?.sha256)
        errors.push('Installed Design DNA does not match manifest DNA hash');
    } catch (error) {
      errors.push(`Cannot validate installed Design DNA: ${error.message}`);
    }
  }

  return {
    valid: errors.length === 0,
    projectRoot,
    documentId: manifest.dna?.documentId ?? null,
    revision: manifest.dna?.revision ?? null,
    managedArtifactCount: manifest.managedArtifacts?.length ?? 0,
    errors,
  };
}
